<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Represents one install programme generation run per project.
 *
 * Status pipeline: draft → active → complete → archived.
 *
 * Each programme holds a full set of install tasks generated by
 * InstallTaskGeneratorService from ProjectDataService canonical data
 * (room × equipment driven). Only one programme should be active at a time;
 * activeInstallProgramme() on Project enforces this via query scope.
 *
 * @see InstallTask              — child tasks belonging to this programme
 * @see InstallTaskGeneratorService — populates tasks on generation
 * @see Project::installProgrammes() — parent relationship
 */
class InstallProgramme extends Model
{
    use HasFactory, SoftDeletes;

    // ── Status constants ──────────────────────────────────────────────────────

    public const STATUS_DRAFT    = 'draft';
    public const STATUS_ACTIVE   = 'active';
    public const STATUS_COMPLETE = 'complete';
    public const STATUS_ARCHIVED = 'archived';

    // ── Mass-assignable fields ────────────────────────────────────────────────

    protected $fillable = [
        'project_id',
        'generated_by',
        'status',
        'generated_at',
        'activated_at',
        'completed_at',
        'planned_start_date',
        'planned_end_date',
        'notes',
    ];

    // ── Casts ─────────────────────────────────────────────────────────────────

    protected function casts(): array
    {
        return [
            'generated_at'      => 'datetime',
            'activated_at'      => 'datetime',
            'completed_at'      => 'datetime',
            'planned_start_date' => 'date',
            'planned_end_date'   => 'date',
        ];
    }

    // ── Relationships ─────────────────────────────────────────────────────────

    public function project(): BelongsTo
    {
        return $this->belongsTo(Project::class);
    }

    public function generatedBy(): BelongsTo
    {
        return $this->belongsTo(User::class, 'generated_by');
    }

    public function tasks(): HasMany
    {
        return $this->hasMany(InstallTask::class)->orderBy('sort_order');
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    /**
     * Human-readable status label for display.
     */
    public function statusLabel(): string
    {
        return match ($this->status) {
            self::STATUS_DRAFT    => 'Draft',
            self::STATUS_ACTIVE   => 'Active',
            self::STATUS_COMPLETE => 'Complete',
            self::STATUS_ARCHIVED => 'Archived',
            default               => ucfirst($this->status),
        };
    }

    /**
     * CSS badge class matching the Worksheet/OmManual convention.
     */
    public function statusBadgeClass(): string
    {
        return match ($this->status) {
            self::STATUS_DRAFT    => 'badge-yellow',
            self::STATUS_ACTIVE   => 'badge-teal',
            self::STATUS_COMPLETE => 'badge-green',
            self::STATUS_ARCHIVED => 'badge-grey',
            default               => 'badge-grey',
        };
    }

    /**
     * Returns true when this programme is in draft (not yet activated).
     */
    public function isDraft(): bool
    {
        return $this->status === self::STATUS_DRAFT;
    }

    /**
     * Returns true when this programme is the active delivery programme.
     */
    public function isActive(): bool
    {
        return $this->status === self::STATUS_ACTIVE;
    }
}
