<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        $now = now();

        DB::table('solution_types')->insertOrIgnore([

            // ── 13. Conferencing (Teams / Zoom Room) ──────────────────────────
            [
                'name'             => 'Conferencing (Teams / Zoom Room)',
                'slug'             => 'conferencing-teams-zoom-room',
                'description'      => 'Certified Microsoft Teams Room or Zoom Room deployment with dedicated compute, camera, mic array and touch controller.',
                'survey_checklist' => implode("\n", [
                    'Room dimensions (W × D × H)',
                    'Seating capacity and table layout',
                    'Display size and viewing distance to furthest seat',
                    'Ceiling height and speaker/mic mounting options',
                    'Network infrastructure (dedicated VLAN, PoE switch, available bandwidth)',
                    'Teams/Zoom tenant details and IT contact for provisioning',
                    'Power outlets at display wall, table, and equipment location',
                    'Cable containment routes (display wall, table, ceiling void)',
                    'Ambient noise level and acoustic treatment present',
                    'Touch controller mounting location (wall or table)',
                    'Existing VC equipment to retain, replace, or remove',
                    'Camera field of view — confirm no obstructions',
                    'Room booking system integration requirement',
                    'Ventilation/cooling at AV equipment location',
                ]),
                'install_method'   => implode("\n", [
                    '1. First fix — install cable containment, pull AV, USB, data and power cables',
                    '2. Mount display bracket to wall; verify level and structural fixing',
                    '3. Install and connect certified VC camera (PTZ or fixed-angle)',
                    '4. Install and connect room audio system (integrated bar, ceiling mics, or table mic array)',
                    '5. Hang and connect display; dress cables behind bracket',
                    '6. Install compute unit (MTR/Zoom Room engine) in rack or hidden mount',
                    '7. Install and cable touch controller panel at wall or table',
                    '8. Connect all peripherals to compute unit',
                    '9. Power on; complete initial device setup and Windows/Android configuration',
                    '10. Enrol device in Teams/Zoom tenant; configure room account and calendar integration',
                    '11. Test inbound and outbound calls; verify camera, mic, and speaker operation',
                    '12. Configure display name, room settings, and default layout',
                    '13. Conduct sign-off call with IT and end user',
                    '14. Label all cables; complete as-built cable schedule',
                ]),
                'is_active'        => true,
                'sort_order'       => 13,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],

            // ── 14. BYOD Conferencing ─────────────────────────────────────────
            [
                'name'             => 'BYOD Conferencing',
                'slug'             => 'byod-conferencing',
                'description'      => 'Bring-your-own-device huddle or meeting space — USB/HDMI connectivity point, room camera, speakerphone and display with no fixed codec.',
                'survey_checklist' => implode("\n", [
                    'Room dimensions and maximum occupancy',
                    'Table or desk layout and cable management options',
                    'HDMI/USB-C/USB-A connection point location (table cubby, floor box, or wall plate)',
                    'Power outlet at table position for BYOD device charging',
                    'Network availability (wired and wireless for guest devices)',
                    'Existing display or new display required',
                    'Cable routing method (surface trunking, floor box, or concealed)',
                    'Wireless presentation system requirement (e.g. ClickShare, Solstice)',
                    'Room audio requirement (USB speakerphone, ceiling speaker bar, or none)',
                    'USB webcam requirement if no integrated camera',
                    'Lighting conditions at table for camera use',
                ]),
                'install_method'   => implode("\n", [
                    '1. Install cable containment; pull HDMI, USB and power cables to connection point',
                    '2. Mount display bracket; install and connect display',
                    '3. Install table cable cubby, floor box, or wall plate at table position',
                    '4. Fit HDMI, USB-A and USB-C connection plate or cable fly leads',
                    '5. Install room speakerphone or USB speaker bar and connect to connection point',
                    '6. Install USB webcam at display if required',
                    '7. Install wireless presentation system (if in scope)',
                    '8. Test all connections with a BYOD laptop — verify display, audio, and video',
                    '9. Label connections; complete install record',
                ]),
                'is_active'        => true,
                'sort_order'       => 14,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],

            // ── 15. Split / Divisible Room ────────────────────────────────────
            [
                'name'             => 'Split / Divisible Room',
                'slug'             => 'split-divisible-room',
                'description'      => 'Partition-divided space with AV operable independently in each half or combined as a single room — requires switching, separate control, and partition interface cabling.',
                'survey_checklist' => implode("\n", [
                    'Room dimensions in full and split configurations',
                    'Partition/wall type, manufacturer, and acoustic rating (STC value)',
                    'Partition opening mechanism and interface panel locations',
                    'Existing AV in each half (to retain, reuse, or replace)',
                    'Signal switching/distribution method (separate systems or shared switcher)',
                    'Cable routing path through or above partition',
                    'Power and data availability in each half independently',
                    'Control system requirement (separate touchpanels, combined, or linked)',
                    'Microphone coverage required in each configuration',
                    'Display or projection in each half (size, position, mounting)',
                    'IT network segregation requirement when room is split',
                    'Audio bleed between halves — confirm acoustic performance',
                ]),
                'install_method'   => implode("\n", [
                    '1. Agree partition interface points and cable pass-through with main contractor',
                    '2. First fix — install containment and pull cables in each half independently',
                    '3. Install displays or projection system in both halves',
                    '4. Install ceiling or surface speakers and microphones in both halves',
                    '5. Install AV switching and distribution equipment for split and combined modes',
                    '6. Install control system touchpanels in each half',
                    '7. Install partition interface cabling (signal and control pass-through)',
                    '8. Program control system for split (A only), split (B only), and combined modes',
                    '9. Commission audio levels and acoustic echo cancellation in each configuration',
                    '10. Test all operating modes including mid-session partition close/open transitions',
                    '11. Handover and user training on partition AV operation',
                ]),
                'is_active'        => true,
                'sort_order'       => 15,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],

            // ── 16. Projection / Screen System ───────────────────────────────
            [
                'name'             => 'Projection / Screen System',
                'slug'             => 'projection-screen-system',
                'description'      => 'Projector with fixed, motorised or tab-tensioned screen — suitable for training rooms, classrooms, conference rooms and auditoria.',
                'survey_checklist' => implode("\n", [
                    'Room dimensions (W × D × H)',
                    'Throw distance from proposed projector position to screen wall',
                    'Ceiling height and mounting option (ceiling plate, drop rod, beam shelf)',
                    'Structural suitability at projector mount point (solid concrete, timber joist, steel beam)',
                    'Ambient light levels — windows, rooflights, existing blinds or blackout',
                    'Screen type required (fixed frame, motorised cassette, tab-tensioned, short-throw wall)',
                    'Screen size and aspect ratio (16:9, 4:3, 2.35:1)',
                    'Power outlet at projector mounting position',
                    'Signal source locations (lectern, wall plate, table)',
                    'Cable routing from sources to projector position (ceiling void or surface)',
                    'Lens type required (standard, short-throw, ultra short-throw, long-throw)',
                    'Keystone or lens shift constraints from mounting position',
                    'Network connection for projector IP management or lamp monitoring',
                    'Existing projector or screen to remove',
                ]),
                'install_method'   => implode("\n", [
                    '1. Mark out projector mounting position; confirm throw calculation with lens spec sheet',
                    '2. Install structural anchor points — drop rods, unistrut or ceiling bracket',
                    '3. Install cable containment; pull power, HDMI/HDBaseT and control cables',
                    '4. Install motorised screen bracket and cassette, or fixed/tensioned frame',
                    '5. Mount projector to ceiling mount; adjust position on drop rods',
                    '6. Connect signal and control cables to projector',
                    '7. Power on projector; perform lens zoom, shift and focus',
                    '8. Align projected image to screen; correct geometry and keystone',
                    '9. Install and connect AV source switching or wall plates',
                    '10. Integrate motorised screen relay or RS-232/IP control if in scope',
                    '11. Install blackout blinds or integrate with existing motorisation (if in scope)',
                    '12. Test all source inputs; verify contrast and brightness',
                    '13. Log projector serial number, lamp hours and register warranty',
                ]),
                'is_active'        => true,
                'sort_order'       => 16,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],

            // ── 17. Simple Display / TV Install ──────────────────────────────
            [
                'name'             => 'Simple Display / TV Install',
                'slug'             => 'simple-display-tv-install',
                'description'      => 'Single commercial or consumer flat panel installation — wall-mounted with basic source connectivity. No VC system, no CMS.',
                'survey_checklist' => implode("\n", [
                    'Display size and proposed mounting location',
                    'Wall construction (masonry, stud/plasterboard, timber frame, glass partition)',
                    'Structural suitability for bracket weight at proposed position',
                    'Power outlet location and proximity — new socket required?',
                    'Signal source type (HDMI wall plate, media player, set-top box, direct PC)',
                    'Cable routing method (surface trunking, concealed in chase, or skirting)',
                    'Mounting height, tilt and swivel requirements',
                    'Network connection for smart display management or HDMI-CEC',
                    'Existing display to remove and dispose',
                    'Access for installation (step ladders sufficient or MEWP/podium required)',
                ]),
                'install_method'   => implode("\n", [
                    '1. Mark out bracket fixing positions; identify wall construction and select fixings',
                    '2. Install wall bracket — level, anchored to masonry plugs, studs, or specialist fixings',
                    '3. Install cable trunking or cut/chase concealed cable route',
                    '4. Pull power extension or spur and HDMI signal cable to bracket',
                    '5. Hang display on bracket; dress and secure cables behind screen',
                    '6. Connect power and signal inputs; power on',
                    '7. Set input source, picture mode and display name',
                    '8. Adjust tilt and height; confirm viewing angle from seating position',
                    '9. Remove packaging; dispose of old display if in scope',
                ]),
                'is_active'        => true,
                'sort_order'       => 17,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],

            // ── 18. Boardroom / Executive Suite ──────────────────────────────
            [
                'name'             => 'Boardroom / Executive Suite',
                'slug'             => 'boardroom-executive-suite',
                'description'      => 'High-specification integrated AV with touch-panel control system (Crestron, AMX, QSC or Extron), full VC, presentation switching, lighting and blind integration.',
                'survey_checklist' => implode("\n", [
                    'Room dimensions and seating capacity',
                    'Display type and position (wall-hung, ceiling recess, floor-rise, dual screens)',
                    'Table dimensions, material and cable management requirements (wire tray, floor box)',
                    'Touch control panel locations (wall, table-top, credenza)',
                    'VC system type (codec, all-in-one bar, MTR/Zoom Room)',
                    'Camera field of view and position — no obstructions',
                    'Microphone system type (table boundary, ceiling beam-tracking, or gooseneck)',
                    'Ceiling speaker positions and driver size',
                    'Lighting control integration (manufacturer, protocol — DALI, DMX, Lutron)',
                    'Motorised blind/shade integration requirement',
                    'Equipment rack/cabinet location, dimensions and ventilation',
                    'Network infrastructure (dedicated VLAN, available bandwidth, PoE)',
                    'Power positions (table, credenza, rack, display wall)',
                    'Cable containment routes (under floor, ceiling void, wall chases)',
                    'Finish and aesthetics requirements (flush faceplates, cable reveals, RAL colour)',
                    'IT/BMS integration points and contacts',
                    'Existing AV equipment to retain, integrate, or remove',
                ]),
                'install_method'   => implode("\n", [
                    '1. Co-ordinate first fix programme with main contractor (containment, back boxes, conduit)',
                    '2. Install cable containment throughout; pull all AV, control, data and power cables',
                    '3. Install display brackets, screen housing, ceiling apertures or floor-rise mechanism',
                    '4. Install and connect all displays and screens',
                    '5. Build rack/equipment cabinet — install rails, power distribution, patch panels',
                    '6. Install and connect VC system (camera, codec/compute, speaker bar or ceiling array)',
                    '7. Install in-ceiling speakers and connect to amplifier',
                    '8. Install microphone system (table mics, gooseneck or beam-tracking ceiling array)',
                    '9. Install control system processor; complete system wiring to control ports',
                    '10. Install touchpanels at wall and/or table positions',
                    '11. Load control system program; commission all device drivers',
                    '12. Integrate with lighting, motorised blinds and room booking system',
                    '13. Commission audio DSP — levels, EQ, gain structure, echo cancellation',
                    '14. Test all VC calls and presentation source switching',
                    '15. Conduct 48-hour AV soak test',
                    '16. Handover walkthrough and user training session; complete O&M pack',
                ]),
                'is_active'        => true,
                'sort_order'       => 18,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],

            // ── 19. IPTV / Satellite Distribution ────────────────────────────
            [
                'name'             => 'IPTV / Satellite Distribution',
                'slug'             => 'iptv-satellite-distribution',
                'description'      => 'Multi-room TV and video distribution — headend encoding/modulation with IPTV decoders, satellite or Freeview reception to multiple display locations.',
                'survey_checklist' => implode("\n", [
                    'Number of display locations and floor plan layout',
                    'Signal sources required (Sky, Virgin, Freeview, IPTV headend, streaming services)',
                    'Existing cabling infrastructure (coax, Cat6, fibre)',
                    'Network infrastructure (bandwidth, IGMP snooping enabled, multicast routing)',
                    'Headend/equipment room location and available rack space',
                    'Power availability at headend location',
                    'Display mounting positions (existing or new)',
                    'Number of channels required simultaneously',
                    'Interactive or non-interactive (non-zapping) requirement',
                    'Audio zone distribution requirement alongside video',
                    'Remote management/monitoring requirement',
                ]),
                'install_method'   => implode("\n", [
                    '1. Install headend rack enclosure and power distribution',
                    '2. Install satellite dish or aerial at roof/external location; run coax to headend',
                    '3. Install and configure encoding/modulation equipment (encoders, IP streamers)',
                    '4. Install IPTV headend server and configure channel lineup and EPG',
                    '5. Install Cat6 or coax distribution cabling to all display locations',
                    '6. Install IPTV set-top boxes or decoders at each display',
                    '7. Connect decoders to displays; configure input sources',
                    '8. Test all channels at all display locations',
                    '9. Configure remote control pairing at each location',
                    '10. Test interactive features and EPG navigation',
                    '11. Document channel lineup and handover login credentials to client IT',
                ]),
                'is_active'        => true,
                'sort_order'       => 19,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],

            // ── 20. Stage / Event Infrastructure ─────────────────────────────
            [
                'name'             => 'Stage / Event Infrastructure',
                'slug'             => 'stage-event-infrastructure',
                'description'      => 'Permanent or semi-permanent stage and event space — PA system, stage monitoring, projection or LED, lighting rig, video switching and FOH infrastructure.',
                'survey_checklist' => implode("\n", [
                    'Stage dimensions (W × D) and clear height to ceiling or truss',
                    'Rigging points available (flying) — rated load per point',
                    'Load-bearing capacity of ceiling, beams or dedicated truss',
                    'Power distribution available (three-phase, 32A/63A commando sockets, UPS)',
                    'Throw distance and surface for projection or LED screen',
                    'PA coverage area and audience capacity',
                    'Stage monitoring requirement (wedges, in-ear, or none)',
                    'Acoustic environment (RT60, background noise, reflective surfaces)',
                    'Lighting rig positions and existing dimmer/DMX infrastructure',
                    'Video switching and streaming or recording requirement',
                    'Comms/IEM (in-ear monitor) system requirement',
                    'FOH (front of house) position — sightlines and cable route',
                    'Cable management across stage area (cable ramps, trays, conduit)',
                    'Adjacent areas for FOH mix position and backstage rack',
                ]),
                'install_method'   => implode("\n", [
                    '1. Structural survey and rigging inspection; obtain engineer sign-off on flying loads',
                    '2. Install truss or rigging system; safety bond all flown equipment',
                    '3. Install power distribution (distro boxes, stage-pin or commando outlets, data cabling)',
                    '4. Fly or ground-stack PA speaker system; run speaker cable to amplifier rack',
                    '5. Install stage monitor wedges and connect to amplifier/DSP',
                    '6. Install front fills or under-stage speakers if required',
                    '7. Install projection system or LED screen (fly or ground support)',
                    '8. Install lighting rig; patch dimmer circuits and DMX universe',
                    '9. Install video switcher, streaming encoder and recording infrastructure',
                    '10. Commission audio system — set gain structure, DSP routing, system drive',
                    '11. Commission lighting rig; program house, wash and spot scenes',
                    '12. Test all signal paths end-to-end from sources to outputs',
                    '13. Full technical run-through with event team; adjust mix and levels',
                    '14. Complete as-built drawings, patch schedules and handover documentation',
                ]),
                'is_active'        => true,
                'sort_order'       => 20,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],

            // ── 21. Acoustic Treatment ────────────────────────────────────────
            [
                'name'             => 'Acoustic Treatment',
                'slug'             => 'acoustic-treatment',
                'description'      => 'Supply and installation of acoustic absorber panels, diffusers and bass traps to achieve a target RT60 or improve speech intelligibility in meeting, recording or teaching spaces.',
                'survey_checklist' => implode("\n", [
                    'Room dimensions and volume (calculate cubic metres)',
                    'Current RT60 measurement or estimated reverberation time',
                    'Wall, floor and ceiling surface materials and finishes',
                    'Target RT60 or acoustic performance specification (e.g. BB93, BS 8233)',
                    'Proposed positions for absorbers, diffusers and bass traps',
                    'Wall and ceiling fixing suitability at proposed panel positions',
                    'Aesthetic requirements (fabric colour, panel profile, edge detail, RAL colour)',
                    'Existing acoustic treatment to remove',
                    'Furniture and room layout impact on treatment positions',
                    'Access for installation (step ladders or podium)',
                ]),
                'install_method'   => implode("\n", [
                    '1. Survey and agree panel positions with acoustic consultant and client',
                    '2. Mark out panel locations; confirm fixing suitability (masonry, plasterboard, timber)',
                    '3. Install timber battens or sub-frame where direct fixing is not suitable',
                    '4. Fix acoustic absorber panels to walls at agreed positions',
                    '5. Install corner bass traps — floor to ceiling or ceiling corner units',
                    '6. Fix diffuser panels at reflection points as specified',
                    '7. Install ceiling-mounted baffles or clouds if in scope',
                    '8. Measure RT60 post-installation using calibrated microphone and software',
                    '9. Review result against target; adjust panel quantity or position if needed',
                    '10. Final sign-off RT60 measurement; issue acoustic report to client',
                ]),
                'is_active'        => true,
                'sort_order'       => 21,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],

        ]);
    }

    public function down(): void
    {
        DB::table('solution_types')->whereIn('slug', [
            'conferencing-teams-zoom-room',
            'byod-conferencing',
            'split-divisible-room',
            'projection-screen-system',
            'simple-display-tv-install',
            'boardroom-executive-suite',
            'iptv-satellite-distribution',
            'stage-event-infrastructure',
            'acoustic-treatment',
        ])->delete();
    }
};
