<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

/**
 * Fixes two schema issues that break the upload pipeline:
 *
 *  1. filename — was NOT NULL; upload records have no DOCX filename yet.
 *     Changed to nullable so Phase A records can be created before generation.
 *
 *  2. status column default — was 'for_review' (legacy workflow default).
 *     Changed to 'uploaded' so any record created without an explicit status
 *     correctly reflects the upload pipeline starting state.
 *
 * Both changes are idempotent-safe via hasColumn checks.
 * The raw ALTER COLUMN DEFAULT statement is MySQL-only and is skipped on SQLite.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::table('rams_documents', function (Blueprint $table) {
            // 1. Make filename nullable so upload records can be created before
            //    the DOCX is generated by Phase B.
            $table->string('filename')->nullable()->change();
        });

        // 2. Change the status column default from 'for_review' to 'uploaded'.
        //    The column type varies across environments (enum vs string) so we
        //    use a raw ALTER rather than Blueprint to avoid driver-specific issues.
        //    SQLite does not support ALTER COLUMN — skip on SQLite.
        if (DB::getDriverName() !== 'sqlite') {
            DB::statement(
                "ALTER TABLE rams_documents ALTER COLUMN status SET DEFAULT 'uploaded'"
            );
        }
    }

    public function down(): void
    {
        Schema::table('rams_documents', function (Blueprint $table) {
            $table->string('filename')->nullable(false)->change();
        });

        if (DB::getDriverName() !== 'sqlite') {
            DB::statement(
                "ALTER TABLE rams_documents ALTER COLUMN status SET DEFAULT 'for_review'"
            );
        }
    }
};
