<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Creates the install_programmes table for the Installation Programme module.
 *
 * Each install programme is tied to a project and tracks the auto-generated
 * task list for that installation run. Status pipeline: draft → active →
 * complete → archived. Generated by InstallTaskGeneratorService from
 * ProjectDataService canonical data (room × equipment driven).
 */
return new class extends Migration
{
    public function up(): void
    {
        /**
         * install_programmes — one generation run per project.
         *
         * Status values: draft | active | complete | archived
         * generated_by references the user who triggered generation.
         * planned_start_date / planned_end_date set by admin before activation.
         */
        Schema::create('install_programmes', function (Blueprint $table) {
            $table->id();

            $table->foreignId('project_id')
                  ->nullable()
                  ->constrained('projects')
                  ->nullOnDelete();

            $table->foreignId('generated_by')
                  ->nullable()
                  ->constrained('users')
                  ->nullOnDelete();

            $table->string('status', 30)->default('draft');
            // draft | active | complete | archived

            $table->timestamp('generated_at')->nullable();
            $table->timestamp('activated_at')->nullable();
            $table->timestamp('completed_at')->nullable();

            $table->date('planned_start_date')->nullable();
            $table->date('planned_end_date')->nullable();

            $table->text('notes')->nullable();

            $table->timestamps();
            $table->softDeletes();

            $table->index('project_id');
            $table->index('status');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('install_programmes');
    }
};
