<?php

namespace Tests\Unit\Services\Rams;

use App\Services\Rams\RamsComplianceUpgradeService;
use Tests\TestCase;

/**
 * Phase 30 Plan 08 (GATE-14) — throw/no-throw... except there is no throw.
 * `enforceMissingRiskRefGate()` is WARN TIER (RESEARCH.md Finding 7, D-04):
 * a violation appends to `compliance_warnings` and the method NEVER throws,
 * on any input, because `associated_risks` is app-generated by
 * `crossReferenceMethodStatementRisks()` and an engineer cannot fix a
 * violation from any UI field.
 *
 * This file's assertion style has no analog elsewhere in the repo: every
 * other gate test asserts a throw or `assertSame($data, $result)`. This one
 * asserts on the returned `compliance_warnings` array's contents — closer
 * in shape to `StructuralGatesTest`'s GATE-04 warn-path tests than to any
 * throwing gate test. Reflection is used to invoke the private static
 * directly, mirroring `HotWorksGateTest`/`CdmEmergencyGateTest`.
 *
 * Every fixture in this file is fed DIRECTLY to `enforceMissingRiskRefGate()`
 * via reflection, bypassing `crossReferenceMethodStatementRisks()` entirely
 * — so `associated_risks` is exactly what each test sets, never
 * auto-computed by `$keywordRiskMap`. This is deliberate: it isolates
 * GATE-14's own logic from the unrelated intersection-based auto-citation
 * this gate exists to catch the failure of. `StructuralGatesDisarmedTest`'s
 * new D-04 leg (Plan 30-08) separately proves the two interact correctly
 * through the real `upgrade()` entry point.
 *
 * ── Non-vacuity proof (development-time only, not a committed assertion) ──
 *
 * Procedure followed during development, mirroring `HotWorksGateTest`'s
 * documented "break-the-fix-and-watch-the-test-fail" procedure:
 *
 *   1. Temporarily changed `findHazardIndexForSignal()`'s return to always
 *      `return null;` (simulating "implied hazard never resolves").
 *   2. Re-ran `php artisan test --filter=MissingRiskRefGateTest`.
 *   3. Result: every warning-producing test failed (empty
 *      `compliance_warnings` where warnings were expected); the
 *      never-fires tests (absent hazard, already cited, malformed input)
 *      were unaffected — proving the warning tests are not vacuously
 *      passing.
 *   4. Restored the real implementation (confirmed `git diff` empty
 *      afterward).
 *   5. Re-ran the filter again: all tests passed, confirming the restore.
 *
 * @see app/Services/Rams/RamsComplianceUpgradeService.php
 * @see app/Services/Rams/StructuralGateVocabulary.php
 * @see .planning/phases/30-structural-validation-gates/30-08-PLAN.md
 * @see .planning/phases/30-structural-validation-gates/30-RESEARCH.md (Finding 7)
 */
class MissingRiskRefGateTest extends TestCase
{
    private function invokePrivateStatic(string $method, array $args = []): mixed
    {
        $m = new \ReflectionMethod(RamsComplianceUpgradeService::class, $method);
        $m->setAccessible(true);

        return $m->invoke(null, ...$args);
    }

    private function enforceMissingRiskRefGate(array $data): array
    {
        return $this->invokePrivateStatic('enforceMissingRiskRefGate', [$data]);
    }

    // ── Canonical Step-4 defect: two implied-but-uncited hazards ────────────

    public function test_warns_twice_on_the_canonical_step4_defect_naming_both_hazards_by_ra_number(): void
    {
        $data = [
            'hazards' => [
                ['hazard' => 'Working at height (high level mount)'],
                ['hazard' => 'Confined space — ceiling void access'],
                ['hazard' => 'Electrical isolation'],
            ],
            'method_statement' => [
                'phases' => [
                    [
                        'title' => 'Display & Mount Installation',
                        'steps' => [
                            'Lift the display onto the wall mount above 2m.',
                            'Access above the ceiling grid via the ceiling void.',
                        ],
                        // Cites only the unrelated third hazard — RA01/RA02
                        // (the two implied hazards) are both uncited.
                        'associated_risks' => [3],
                    ],
                ],
            ],
        ];

        $result = $this->enforceMissingRiskRefGate($data);

        $this->assertCount(2, $result['compliance_warnings']);

        $indexes = array_column($result['compliance_warnings'], 'hazard_index');
        sort($indexes);
        $this->assertSame([0, 1], $indexes);

        foreach ($result['compliance_warnings'] as $warning) {
            $this->assertSame('GATE-14', $warning['gate']);
            $this->assertSame('Display & Mount Installation', $warning['step_title']);
            $this->assertMatchesRegularExpression('/GATE-14/', $warning['message']);
            $this->assertMatchesRegularExpression('/RA0[12]/', $warning['message']);
        }
    }

    public function test_a_phase_matching_two_phrases_for_the_same_hazard_produces_only_one_warning(): void
    {
        // 'wall mount' and 'above 2m' both map to signal mounting_above_reach
        // (config/rams_tier1.php missing_risk_implications) and both resolve
        // to the SAME hazard row here — must not double-warn.
        $data = [
            'hazards' => [
                ['hazard' => 'Working at height (high level mount)'],
            ],
            'method_statement' => [
                'phases' => [
                    [
                        'title' => 'Display & Mount Installation',
                        'steps' => ['Lift the display onto the wall mount above 2m.'],
                        'associated_risks' => [],
                    ],
                ],
            ],
        ];

        $result = $this->enforceMissingRiskRefGate($data);

        $this->assertCount(1, $result['compliance_warnings']);
        $this->assertSame(0, $result['compliance_warnings'][0]['hazard_index']);
    }

    // ── Does not fire when the implied hazard is ABSENT from the register ──

    public function test_does_not_fire_when_the_implied_hazard_is_absent_from_the_register(): void
    {
        $data = [
            'hazards' => [
                ['hazard' => 'Electrical isolation'],
            ],
            'method_statement' => [
                'phases' => [
                    [
                        'title' => 'Display & Mount Installation',
                        'steps' => ['Lift the display onto the wall mount above 2m.'],
                        'associated_risks' => [],
                    ],
                ],
            ],
        ];

        $result = $this->enforceMissingRiskRefGate($data);

        $this->assertSame([], $result['compliance_warnings']);
    }

    // ── Does not fire when the implied hazard is already cited ─────────────

    public function test_does_not_fire_when_the_implied_hazard_is_already_cited(): void
    {
        $data = [
            'hazards' => [
                ['hazard' => 'Working at height (high level mount)'],
            ],
            'method_statement' => [
                'phases' => [
                    [
                        'title' => 'Display & Mount Installation',
                        'steps' => ['Lift the display onto the wall mount above 2m.'],
                        // RA01 already cited — no citation gap.
                        'associated_risks' => [1],
                    ],
                ],
            ],
        ];

        $result = $this->enforceMissingRiskRefGate($data);

        $this->assertSame([], $result['compliance_warnings']);
    }

    // ── Never throws, on any input ──────────────────────────────────────────

    public function test_never_throws_on_a_battery_of_malformed_and_empty_inputs(): void
    {
        $inputs = [
            [],
            ['hazards' => []],
            ['method_statement' => []],
            ['hazards' => [], 'method_statement' => ['phases' => []]],
            ['hazards' => ['not an array'], 'method_statement' => ['phases' => [['title' => 'x', 'steps' => ['wall mount']]]]],
            ['hazards' => [['hazard' => 'Working at height']], 'method_statement' => ['phases' => ['not an array']]],
            ['hazards' => [['hazard' => 'Working at height']], 'method_statement' => ['phases' => [['title' => null, 'steps' => null]]]],
            ['hazards' => [null], 'method_statement' => ['phases' => [['title' => 'wall mount ceiling void above 2m podium stepladder', 'steps' => []]]]],
        ];

        foreach ($inputs as $input) {
            $result = $this->enforceMissingRiskRefGate($input);
            $this->assertIsArray($result, 'enforceMissingRiskRefGate() must never throw and must always return an array.');
            // Matches the established early-return convention (e.g.
            // enforceResidualScoreGate()'s `if (empty($hazards)) { return
            // $data; }`): a genuinely empty/malformed input is returned
            // UNCHANGED, so compliance_warnings is only guaranteed present
            // when this method's own input already carried it (as it
            // always does inside the real upgrade() pipeline, which
            // initialises it unconditionally before any gate runs).
        }
    }

    // ── A clean document leaves compliance_warnings as it found it ─────────

    public function test_a_clean_document_leaves_compliance_warnings_as_it_found_it(): void
    {
        $data = [
            'compliance_warnings' => [['gate' => 'GATE-04', 'hazard_index' => 5, 'hazard' => 'x', 'message' => 'pre-existing']],
            'hazards' => [
                ['hazard' => 'Electrical isolation'],
            ],
            'method_statement' => [
                'phases' => [
                    ['title' => 'Commissioning', 'steps' => ['Power on the system and test.'], 'associated_risks' => []],
                ],
            ],
        ];

        $result = $this->enforceMissingRiskRefGate($data);

        $this->assertSame($data['compliance_warnings'], $result['compliance_warnings']);
    }

    // ── Dispatch-flag wiring, through the real upgrade() entry point ───────

    /**
     * A fixture deliberately designed so `crossReferenceMethodStatementRisks()`
     * (which runs unconditionally, before either flag check) does NOT
     * auto-cite the implied hazard via its own `$keywordRiskMap` — the
     * phase text and hazard name share no `$keywordRiskMap` keyword, so
     * `associated_risks` comes back empty for this phase regardless of
     * GATE-14's flag, and GATE-14 (when armed) has a genuine citation gap
     * to find rather than one the app's own auto-citation already closed.
     */
    private function realUpgradeFixture(): array
    {
        return [
            'hazards' => [
                ['hazard' => 'High level mount hazard (falls from height)'],
            ],
            'method_statement' => [
                'phases' => [
                    ['title' => 'Roof Access Task', 'steps' => ['Operatives will use a stepladder for this task.']],
                ],
            ],
        ];
    }

    public function test_with_the_flag_false_the_method_is_never_called_via_upgrade(): void
    {
        config(['rams_tier1.missing_risk_ref_gate_enabled' => false]);

        $result = RamsComplianceUpgradeService::upgrade($this->realUpgradeFixture());

        $gate14Warnings = array_filter($result['compliance_warnings'], fn ($w) => $w['gate'] === 'GATE-14');
        $this->assertSame([], array_values($gate14Warnings));
    }

    public function test_with_the_flag_true_the_method_runs_via_upgrade_and_warns(): void
    {
        config(['rams_tier1.missing_risk_ref_gate_enabled' => true]);

        $result = RamsComplianceUpgradeService::upgrade($this->realUpgradeFixture());

        $gate14Warnings = array_values(array_filter($result['compliance_warnings'], fn ($w) => $w['gate'] === 'GATE-14'));
        $this->assertCount(1, $gate14Warnings);
        $this->assertSame(0, $gate14Warnings[0]['hazard_index']);
    }
}
