<?php

namespace App\Core\Modules\Survey;

use App\Core\Modules\Projects\ProjectService;
use App\Jobs\GenerateSurveyQuestionsJob;
use App\Mail\SurveySubmittedMail;
use App\Models\Project;
use App\Models\ProjectActivityLog;
use App\Models\SiteSurvey;
use App\Models\SiteSurveyPhoto;
use App\Models\SiteSurveyRoom;
use App\Models\User;
use App\Services\ProjectContextResolver;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

class SurveyService
{
    public function __construct(
        private readonly ProjectService        $projects,
        private readonly ProjectContextResolver $contextResolver,
    ) {}

    // ─── Survey CRUD ─────────────────────────────────────────────────────────

    /**
     * Create a new survey with rooms (no photos at creation time).
     *
     * One-survey-per-project enforcement:
     * - If $data['supersede'] is truthy and a project_id is present, any existing
     *   non-superseded survey for that project is atomically archived before the
     *   new survey is created (within the same DB transaction).
     * - If $data['supersede'] is absent/false and an active survey already exists
     *   for the given project_id, a RuntimeException is thrown. The controller
     *   surfaces the supersede confirmation UI before reaching this guard.
     *
     * @throws \RuntimeException when a duplicate active survey exists and supersede flag is absent.
     */
    public function create(User $user, array $data): SiteSurvey
    {
        return DB::transaction(function () use ($user, $data) {
            // ── One-survey enforcement ─────────────────────────────────────────
            if (! empty($data['project_id'])) {
                $existing = SiteSurvey::where('project_id', $data['project_id'])
                    ->whereNull('superseded_at')
                    ->whereIn('status', ['draft', 'completed'])
                    ->first();

                if ($existing) {
                    if (! empty($data['supersede'])) {
                        $this->supersedeSurvey($existing);
                    } else {
                        throw new \RuntimeException(
                            'Project already has an active survey. Use supersede flag to replace it.'
                        );
                    }
                }
            }

            $survey = SiteSurvey::create([
                'user_id'       => $user->id,
                'project_id'    => $data['project_id']    ?? null,
                'project_name'  => $data['project_name'],
                'project_ref'   => $data['project_ref']   ?? null,
                'client_name'   => $data['client_name']   ?? null,
                'site_address'  => $data['site_address']  ?? null,
                'survey_date'   => $data['survey_date']   ?? null,
                'surveyor_name' => $data['surveyor_name'] ?? null,
                'general_notes' => $data['general_notes'] ?? null,
                'status'        => 'draft',
                'survey_type'   => $data['survey_type']   ?? 'general',
            ]);

            foreach ($data['rooms'] ?? [] as $i => $room) {
                $this->createRoom($survey, $room, $i);
            }

            if ($survey->project_id) {
                /** @var Project $project */
                $project = Project::find($survey->project_id);
                $this->projects->logDocument($project, $user, 'site-survey', $survey->id);
            }

            return $survey;
        });
    }

    /**
     * Pre-create a survey from a project's reviewed package data.
     *
     * Rooms are seeded from room_overviews in the latest ProjectPackage's
     * extracted_data. The survey header is pre-filled from the Project model.
     * The access token is auto-generated by SiteSurvey::boot().
     *
     * One-survey-per-project enforcement mirrors create():
     * - $supersede=true archives any existing active survey atomically.
     * - $supersede=false throws RuntimeException if an active survey exists.
     *
     * Activity is logged as 'survey_created' on the project.
     *
     * @throws \RuntimeException when a duplicate active survey exists and $supersede is false.
     */
    public function createFromProject(Project $project, User $user, bool $supersede = false): SiteSurvey
    {
        return DB::transaction(function () use ($project, $user, $supersede) {
            // ── One-survey enforcement ─────────────────────────────────────────
            $existing = SiteSurvey::where('project_id', $project->id)
                ->whereNull('superseded_at')
                ->whereIn('status', ['draft', 'completed'])
                ->first();

            if ($existing) {
                // If the existing survey hasn't been touched by an engineer
                // yet, regen has nothing to preserve — discard it instead of
                // superseding. Without this, every Regen click accumulates an
                // empty husk in the DB (see survey-15 stranded data incident).
                // "Touched" = surveyor name set, OR survey_data has any room
                // with non-default canonical fields, OR any room photo, OR
                // any pre-install question answered. This deliberately ignores
                // the av_requirements column because that's seeded by us.
                if ($supersede && $this->surveyIsUntouched($existing)) {
                    Log::info('SurveyService: discarding empty existing survey before regen', [
                        'project_id' => $project->id,
                        'survey_id'  => $existing->id,
                    ]);
                    $existing->rooms()->each(function ($room) {
                        $this->deleteRoomPhotos($room);
                        $room->questions()->delete();
                        $room->delete();
                    });
                    $existing->forceDelete();
                } elseif ($existing) {
                    if ($supersede) {
                        $this->supersedeSurvey($existing);
                    } else {
                        throw new \RuntimeException(
                            'Project already has an active survey. Use supersede flag to replace it.'
                        );
                    }
                }
            }

            $ctx   = $this->contextResolver->resolve($project);
            $rooms = $ctx['rooms'];  // [['room' => string, 'overview' => string, 'summary' => string], ...]

            // Group quote equipment by area so each seeded room gets its own
            // kit string (av_equipment_list) — engineers need this context
            // on-site when completing the survey. Key is a lowercased/trimmed
            // area so case/whitespace variants collapse to the same room.
            $equipmentByRoomKey = $this->groupEquipmentByRoom($ctx['equipment'] ?? []);

            $survey = SiteSurvey::create([
                'user_id'       => $user->id,
                'project_id'    => $project->id,
                'project_name'  => $project->name,
                'project_ref'   => $project->ref,
                'client_name'   => $project->client_name,
                'site_address'  => $project->site_address,
                'survey_date'   => null,
                'surveyor_name' => null,
                'general_notes' => null,
                'status'        => 'draft',
                // access_token is auto-generated in SiteSurvey::boot()
            ]);

            // Seed one SiteSurveyRoom per room_overview entry. Skip "rooms"
            // that are actually quote line-items rather than physical spaces
            // (Cabling, Professional Services, Support Services, etc.) —
            // engineers don't survey those, and seeding them as rooms wastes
            // time and clutters the survey wizard.
            foreach ($rooms as $i => $roomData) {
                $roomName = trim((string) ($roomData['room'] ?? ''));
                if ($roomName === '') {
                    continue;
                }
                if ($this->isNonPhysicalRoomLabel($roomName)) {
                    continue;
                }

                // Use solution type checklist as AV requirements if available,
                // otherwise fall back to the overview text.
                $avRequirements = trim((string) ($roomData['overview'] ?? $roomData['summary'] ?? ''));
                $solutionTypeId = (int) ($roomData['solution_type_id'] ?? 0) ?: null;
                if ($solutionTypeId) {
                    $st = \App\Models\SolutionType::find($solutionTypeId);
                    if ($st && $st->survey_checklist) {
                        $avRequirements = $st->survey_checklist;
                    }
                }

                // Deterministic per-room kit string. Falls back to the room's
                // works_summary when the quote didn't itemise equipment under
                // this room's area.
                $kitList = $this->kitListForRoom($roomName, $equipmentByRoomKey)
                    ?: trim((string) ($roomData['works_summary'] ?? ''));

                $room = $survey->rooms()->create($this->roomAttributes([
                    'room_name'         => $roomName,
                    'av_requirements'   => $avRequirements ?: null,
                    'av_equipment_list' => $kitList !== '' ? $kitList : null,
                    'space_type'        => $solutionTypeId
                        ? (\App\Models\SolutionType::find($solutionTypeId)?->slug ?? 'general')
                        : 'general',
                ], $i));

                // Dispatch question generation job for rooms with a known solution type (D-10).
                // The database queue driver defers actual dispatch until after the outer transaction
                // commits, so the room record is guaranteed to exist when the job runs.
                if ($solutionTypeId) {
                    try {
                        GenerateSurveyQuestionsJob::dispatch($room->id);
                    } catch (\Throwable $e) {
                        // Job dispatch failure must not abort the survey creation transaction.
                        Log::warning('SurveyService: could not dispatch GenerateSurveyQuestionsJob', [
                            'room_id' => $room->id,
                            'error'   => $e->getMessage(),
                        ]);
                    }
                }
            }

            // If no rooms were extracted, leave the survey with zero rooms —
            // the engineer will add them manually via the public link.

            // Log survey_created activity on the project.
            $this->projects->log(
                project:     $project,
                user:        $user,
                action:      'survey_created',
                description: "{$user->name} created a site survey for this project.",
                metadata:    ['survey_id' => $survey->id],
            );

            return $survey;
        });
    }

    /**
     * Update survey header + all rooms (full replace of rooms list).
     */
    public function update(SiteSurvey $survey, User $user, array $data): SiteSurvey
    {
        return DB::transaction(function () use ($survey, $user, $data) {
            $survey->update([
                'project_id'    => $data['project_id']    ?? $survey->project_id,
                'project_name'  => $data['project_name']  ?? $survey->project_name,
                'project_ref'   => $data['project_ref']   ?? null,
                'client_name'   => $data['client_name']   ?? null,
                'site_address'  => $data['site_address']  ?? null,
                'survey_date'   => $data['survey_date']   ?? null,
                'surveyor_name' => $data['surveyor_name'] ?? null,
                'general_notes' => $data['general_notes'] ?? null,
                'survey_type'   => $data['survey_type']   ?? $survey->survey_type,
                // Engineer-feedback site logistics (quick task 260503-rgg)
                'comms_room_access_status' => $data['comms_room_access_status'] ?? null,
                'comms_room_access_notes'  => $data['comms_room_access_notes']  ?? null,
                'parking_restraints'       => $data['parking_restraints']       ?? null,
                'distance_from_base_miles' => $data['distance_from_base_miles'] ?? null,
                'distance_from_base_notes' => $data['distance_from_base_notes'] ?? null,
                'site_access_notes'        => $data['site_access_notes']        ?? null,
                'delivery_routes'          => $data['delivery_routes']          ?? null,
            ]);

            // Rebuild rooms: keep existing IDs where supplied to preserve photos
            $incomingIds = collect($data['rooms'] ?? [])->pluck('id')->filter()->all();
            $survey->rooms()->whereNotIn('id', $incomingIds)->each(function (SiteSurveyRoom $r) {
                $this->deleteRoomPhotos($r);
                $r->delete();
            });

            $sortIndex = 0;
            foreach ($data['rooms'] ?? [] as $roomData) {
                if (!empty($roomData['id'])) {
                    $room = SiteSurveyRoom::find($roomData['id']);
                    if ($room && $room->site_survey_id === $survey->id) {
                        $room->update($this->roomAttributes($roomData, $sortIndex++));
                        continue;
                    }
                }
                // Qty > 1: expand into numbered copies (e.g. "Small Room" × 3
                // becomes "Small Room 1", "Small Room 2", "Small Room 3").
                $qty      = max(1, (int) ($roomData['qty'] ?? 1));
                $baseName = trim((string) ($roomData['room_name'] ?? ''));
                if ($qty > 1) {
                    for ($q = 1; $q <= $qty; $q++) {
                        $copy              = $roomData;
                        $copy['room_name'] = "{$baseName} {$q}";
                        $this->createRoom($survey, $copy, $sortIndex++);
                    }
                } else {
                    $this->createRoom($survey, $roomData, $sortIndex++);
                }
            }

            if ($survey->project_id) {
                $project = Project::find($survey->project_id);
                if ($project) {
                    $this->projects->logDocument($project, $user, 'site-survey', $survey->id, 'updated');
                }
            }

            return $survey->fresh();
        });
    }

    /**
     * Mark survey as completed and (optionally) link to a project.
     */
    public function complete(SiteSurvey $survey, User $user, ?int $projectId = null): SiteSurvey
    {
        $survey->update([
            'status'     => 'completed',
            'project_id' => $projectId ?? $survey->project_id,
        ]);

        if ($survey->project_id) {
            $project = Project::find($survey->project_id);
            if ($project) {
                $this->projects->logDocument($project, $user, 'site-survey', $survey->id, 'completed');

                // ── Auto-advance: survey submitted → engineering (D-18, Hook 2) ──
                if ($project->canTransitionTo(Project::STATUS_ENGINEERING)) {
                    try {
                        $this->projects->transition(
                            $project,
                            Project::STATUS_ENGINEERING,
                            $user
                        );
                    } catch (\InvalidArgumentException) {
                        Log::warning('SurveyService: auto-advance to engineering skipped', [
                            'project_id'  => $project->id,
                            'survey_id'   => $survey->id,
                            'from_status' => $project->status,
                        ]);
                    }
                }
            }
        }

        return $survey;
    }

    /**
     * Save a draft update from the public (unauthenticated) survey form.
     *
     * Only updates the header fields and existing rooms. Does NOT add rooms,
     * does NOT change status. Leaves submitted_at null.
     */
    public function saveDraftPublic(SiteSurvey $survey, array $data): SiteSurvey
    {
        return DB::transaction(function () use ($survey, $data) {
            $survey->update([
                'survey_date'        => $data['survey_date']        ?? $survey->survey_date,
                'surveyor_name'      => $data['surveyor_name']      ?? $survey->surveyor_name,
                'general_notes'      => $data['general_notes']      ?? $survey->general_notes,
                'site_risks'         => $data['site_risks']         ?? $survey->site_risks,
                'access_constraints' => $data['access_constraints'] ?? $survey->access_constraints,
                'h_and_s_notes'      => $data['h_and_s_notes']      ?? $survey->h_and_s_notes,
            ]);

            foreach ($data['rooms'] ?? [] as $roomData) {
                if (empty($roomData['id'])) {
                    continue;
                }

                $room = SiteSurveyRoom::find((int) $roomData['id']);
                if (! $room || $room->site_survey_id !== $survey->id) {
                    continue;
                }

                $room->update($this->roomAttributes($roomData, $room->sort_order));
            }

            return $survey->fresh();
        });
    }

    /**
     * Submit the final survey from the public (unauthenticated) form.
     *
     * Saves all room data, sets status = 'completed', and stamps submitted_at.
     * Logs a 'survey_submitted' activity on the linked project if present.
     * Sends a PM notification email outside the transaction so a mail failure
     * cannot roll back the survey submission.
     */
    public function submitPublic(SiteSurvey $survey, array $data): SiteSurvey
    {
        $result = DB::transaction(function () use ($survey, $data) {
            $survey->update([
                'survey_date'        => $data['survey_date']        ?? $survey->survey_date,
                'surveyor_name'      => $data['surveyor_name']      ?? $survey->surveyor_name,
                'general_notes'      => $data['general_notes']      ?? $survey->general_notes,
                'site_risks'         => $data['site_risks']         ?? $survey->site_risks,
                'access_constraints' => $data['access_constraints'] ?? $survey->access_constraints,
                'h_and_s_notes'      => $data['h_and_s_notes']      ?? $survey->h_and_s_notes,
                'status'             => 'completed',
                'submitted_at'       => now(),
            ]);

            foreach ($data['rooms'] ?? [] as $roomData) {
                if (empty($roomData['id'])) {
                    continue;
                }

                $room = SiteSurveyRoom::find((int) $roomData['id']);
                if (! $room || $room->site_survey_id !== $survey->id) {
                    continue;
                }

                $room->update($this->roomAttributes($roomData, $room->sort_order));
            }

            // Log on the linked project (no authenticated user in this path).
            if ($survey->project_id) {
                $project = Project::find($survey->project_id);
                if ($project) {
                    ProjectActivityLog::create([
                        'project_id'  => $project->id,
                        'user_id'     => null,
                        'action'      => 'survey_submitted',
                        'description' => "Site survey #{$survey->id} submitted by engineer via public link.",
                        'metadata'    => ['survey_id' => $survey->id],
                    ]);

                    // ── Auto-advance: survey submitted → engineering (D-18, Hook 2) ──
                    if ($project->canTransitionTo(Project::STATUS_ENGINEERING)) {
                        try {
                            $this->projects->transition(
                                $project,
                                Project::STATUS_ENGINEERING,
                                auth()->user() ?? User::find($project->user_id)
                            );
                        } catch (\InvalidArgumentException) {
                            Log::warning('SurveyService: auto-advance to engineering skipped (public submit)', [
                                'project_id'  => $project->id,
                                'survey_id'   => $survey->id,
                                'from_status' => $project->status,
                            ]);
                        }
                    }
                }
            }

            return $survey->fresh();
        });

        // ── PM notification email — outside transaction so mail failure cannot roll back submission ──
        if ($result->project_id) {
            try {
                $project   = Project::find($result->project_id);
                $recipient = app(\App\Services\NotificationRecipientResolver::class)
                    ->resolveProjectRecipient($project);
                if ($recipient?->email) {
                    $completed = $result->rooms()->where('is_completed', true)->count();
                    Mail::to($recipient->email)->send(new SurveySubmittedMail($result, $completed));
                }
            } catch (\Throwable $e) {
                Log::warning('SurveyService: failed to send survey submitted email', [
                    'survey_id' => $result->id,
                    'error'     => $e->getMessage(),
                ]);
            }
        }

        return $result;
    }

    // ─── Photo management ────────────────────────────────────────────────────

    /**
     * Upload a photo for a specific room and persist to storage.
     *
     * Storage path is project-scoped when the survey is linked to a project:
     *   projects/{project_id}/surveys/{survey_id}/{uuid}.{ext}
     *
     * Falls back to the legacy flat directory for standalone surveys:
     *   survey-photos/{uuid}.{ext}
     *
     * The full relative path is stored in SiteSurveyPhoto::filename so that
     * SiteSurveyPhoto::storagePath() can address it correctly.
     */
    public function addPhoto(SiteSurveyRoom $room, UploadedFile $file, ?string $category = null, ?string $caption = null): SiteSurveyPhoto
    {
        // Derive extension from validated MIME type rather than the
        // client-supplied filename. A polyglot file uploaded as image/jpeg
        // but named `shell.jpg.php` would otherwise land on disk with a `.php`
        // extension and become executable if the photos directory ever had
        // PHP enabled — a latent code-execution path we don't need.
        $extension = match ($file->getMimeType()) {
            'image/jpeg'      => 'jpg',
            'image/png'       => 'png',
            'image/webp'      => 'webp',
            'image/gif'       => 'gif',
            'image/heic',
            'image/heif'      => 'heic',
            default           => 'jpg',
        };
        $basename  = Str::uuid() . '.' . $extension;

        // Resolve the survey (may already be loaded as a relationship).
        $survey    = $room->relationLoaded('survey') ? $room->survey : $room->survey()->first();
        $projectId = $survey?->project_id;
        $surveyId  = $room->site_survey_id;

        if ($projectId) {
            $directory      = "projects/{$projectId}/surveys/{$surveyId}";
            $storedFilename = "{$directory}/{$basename}";
        } else {
            $directory      = 'survey-photos';
            $storedFilename = $basename;   // legacy format — storagePath() will prefix
        }

        Storage::disk('local')->putFileAs($directory, $file, $basename);

        $sortOrder = ($room->photos()->max('sort_order') ?? 0) + 1;

        return $room->photos()->create([
            'filename'      => $storedFilename,
            'original_name' => $file->getClientOriginalName(),
            'mime_type'     => $file->getMimeType() ?? 'image/jpeg',
            'category'      => $category,
            'caption'       => $caption,
            'sort_order'    => $sortOrder,
        ]);
    }

    /**
     * Delete a photo record and its file from disk.
     */
    public function deletePhoto(SiteSurveyPhoto $photo): void
    {
        Storage::disk('local')->delete($photo->storagePath());
        $photo->delete();
    }

    // ─── Helpers ─────────────────────────────────────────────────────────────

    private function createRoom(SiteSurvey $survey, array $data, int $index): SiteSurveyRoom
    {
        return $survey->rooms()->create($this->roomAttributes($data, $index));
    }

    private function roomAttributes(array $data, int $index): array
    {
        return [
            'room_name'                 => $data['room_name'],
            'room_ref'                  => $data['room_ref']                  ?? null,
            'floor'                     => $data['floor']                     ?? null,
            'area_type'                 => $data['area_type']                 ?? null,
            'space_type'                => $data['space_type']                ?? 'general',
            // Dimensions / structure
            'room_width_m'              => $data['room_width_m']              ?? null,
            'room_depth_m'              => $data['room_depth_m']              ?? null,
            'room_height_m'             => $data['room_height_m']             ?? null,
            'ceiling_type'              => $data['ceiling_type']              ?? null,
            'ceiling_height_m'          => $data['ceiling_height_m']          ?? null,
            'wall_material'             => $data['wall_material']             ?? null,
            'floor_type'                => $data['floor_type']                ?? null,
            // AV
            'av_requirements'           => $data['av_requirements']           ?? null,
            'av_equipment_list'         => $data['av_equipment_list']         ?? null,
            // Services
            'has_power'                 => ! empty($data['has_power']),
            'has_network'               => ! empty($data['has_network']),
            'power_outlet_count'        => (int) ($data['power_outlet_count'] ?? 0),
            'network_port_count'        => (int) ($data['network_port_count'] ?? 0),
            'network_ssid'              => $data['network_ssid']              ?? null,
            'network_vlan'              => $data['network_vlan']              ?? null,
            'network_switch_port'       => $data['network_switch_port']       ?? null,
            'existing_cabling'          => $data['existing_cabling']          ?? null,
            'requires_additional_power' => ! empty($data['requires_additional_power']),
            // Access
            'access_notes'              => $data['access_notes']              ?? null,
            'notes'                     => $data['notes']                     ?? null,
            'sort_order'                => $index,
            // PA system
            'speaker_count'             => isset($data['speaker_count'])   ? (int) $data['speaker_count']   : null,
            'speaker_type'              => $data['speaker_type']              ?? null,
            'speaker_mounting'          => $data['speaker_mounting']          ?? null,
            'bg_noise_db'               => isset($data['bg_noise_db'])     ? (int) $data['bg_noise_db']     : null,
            // Digital signage
            'display_size_in'           => $data['display_size_in']           ?? null,
            'display_orient'            => $data['display_orient']            ?? null,
            'display_mounting'          => $data['display_mounting']          ?? null,
            // Infrastructure
            'rack_unit_space'           => isset($data['rack_unit_space'])  ? (int) $data['rack_unit_space'] : null,
            'cable_route_desc'          => $data['cable_route_desc']          ?? null,
            'cable_route_from'          => $data['cable_route_from']          ?? null,
            'cable_route_to'            => $data['cable_route_to']            ?? null,
            'is_rack_room'              => isset($data['is_rack_room']) ? (bool) $data['is_rack_room'] : null,
            'projection_throw_m'        => $data['projection_throw_m']        ?? null,
            'viewing_distance_m'        => $data['viewing_distance_m']        ?? null,
            // Upgrade / strip-out
            'existing_condition'        => $data['existing_condition']        ?? null,
            'items_to_remove'           => $data['items_to_remove']           ?? null,
            'items_to_retain'           => $data['items_to_retain']           ?? null,
            // Engineer sign-off
            'engineer_confirmed'        => isset($data['engineer_confirmed']) ? (bool) $data['engineer_confirmed'] : null,
            'engineer_signature_name'   => $data['engineer_signature_name']   ?? null,
            // Engineer-feedback room-level additions (quick task 260503-rgg)
            'mounting_heights'          => $data['mounting_heights']          ?? null,
            'work_at_height_methods'    => $data['work_at_height_methods']    ?? null,
            'cable_routes'              => $this->normalizeCableRoutes($data['cable_routes'] ?? null),
            'wall_construction'         => $data['wall_construction']         ?? null,
            'wall_needs_reinforcement'  => isset($data['wall_needs_reinforcement']) ? (bool) $data['wall_needs_reinforcement'] : null,
            'wall_needs_chase_out'      => isset($data['wall_needs_chase_out'])     ? (bool) $data['wall_needs_chase_out']     : null,
            'wall_needs_conduit'        => isset($data['wall_needs_conduit'])       ? (bool) $data['wall_needs_conduit']       : null,
            'table_info'                => $data['table_info']                ?? null,
            'floor_box_info'            => $data['floor_box_info']            ?? null,
            'brackets_required'         => $this->normalizeBracketRows($data['brackets_required'] ?? null),
        ];
    }

    private function deleteRoomPhotos(SiteSurveyRoom $room): void
    {
        foreach ($room->photos as $photo) {
            Storage::disk('local')->delete($photo->storagePath());
        }
        $room->photos()->delete();
    }

    /**
     * Return true when a room label refers to a quote line-item rather than
     * a physical space — used by createFromProject() to skip seeding rooms
     * the engineer cannot physically survey.
     *
     * Match is case-insensitive on the trimmed label. Numbered variants
     * ("Cabling 1", "Professional Services 2") are also matched so quote
     * imports that expand qty>1 line-items into separate areas don't slip
     * through.
     */
    public function isNonPhysicalRoomLabel(string $name): bool
    {
        $needle = strtolower(trim($name));
        if ($needle === '') return true;

        // Strip any trailing numeric suffix (e.g. "Cabling 1" → "cabling")
        $needle = preg_replace('/\s+\d+$/', '', $needle);

        static $nonPhysical = [
            'cabling', 'cables', 'wiring',
            'consumables', 'consumable',
            'delivery', 'carriage', 'shipping',
            'professional services', 'professional service',
            'support services', 'support service',
            'service contract', 'service contracts',
            'warranty', 'warranties',
            'options', 'option',
            'licencing', 'licensing', 'licences', 'licenses',
            'training',
            'project management', 'pm', 'project manager',
            'travel', 'travel costs',
            'rams', 'method statement',
            'site survey', 'survey',
        ];

        return in_array($needle, $nonPhysical, true);
    }

    /**
     * Return true when an existing survey has nothing engineer-entered on it
     * yet — used by createFromProject() to discard empty regen targets
     * instead of superseding them. Anything seeded by us at creation time
     * (av_requirements, av_equipment_list, default space_type) is ignored.
     *
     * Touched signals (any one is enough):
     *   - surveyor_name set
     *   - any room has a photo
     *   - any pre-install question has been answered
     *   - survey_data has a room with a non-default canonical/ui_state field
     */
    public function surveyIsUntouched(SiteSurvey $survey): bool
    {
        if (! empty(trim((string) $survey->surveyor_name))) return false;

        if ($survey->rooms()->whereHas('photos')->exists())                       return false;
        if ($survey->rooms()->whereHas('questions', fn ($q) => $q->whereNotNull('answer'))->exists()) return false;

        $payload = (array) ($survey->survey_data ?? []);
        foreach ((array) ($payload['rooms'] ?? []) as $room) {
            if (! is_array($room)) continue;

            // ui_state — any non-default toggle / work_type / voice_note
            $ui = (array) ($room['ui_state'] ?? []);
            if (! empty($ui['work_type']))                                return false;
            if (! empty($ui['voice_note']))                               return false;
            foreach (['power_available','network_available','access_issues','working_at_height','client_present'] as $k) {
                if (! empty($ui[$k])) return false;
            }

            // Canonical capture fields
            if (! empty(trim((string) ($room['notes'] ?? ''))))           return false;

            // Infrastructure has any non-default value
            $infra = (array) ($room['infrastructure'] ?? []);
            $power = (array) ($infra['power'] ?? []);
            if (! empty($power['socket_locations']) || ! empty($power['distance_to_screen']) || ! empty($power['spare_capacity'])) return false;
            $net = (array) ($infra['network'] ?? []);
            if (! empty($net['ports_available']) || ! empty($net['vlan_required']) || ! empty($net['switch_location'])) return false;
            $cab = (array) ($infra['cable_routes'] ?? []);
            if (! empty($cab['route_type']) || ! empty($cab['estimated_distance'])) return false;

            // Equipment / risks / constraints / signoff filled
            if (! empty($room['equipment']))                              return false;
            foreach ((array) ($room['risks'] ?? []) as $risk) {
                if (! is_array($risk)) continue;
                if (! empty($risk['working_height']) && $risk['working_height'] !== '') return false;
                if (! empty($risk['out_of_hours']) || ! empty($risk['permits_required']) || ! empty($risk['manual_handling_risk'])) return false;
            }
            $cons = (array) ($room['constraints'] ?? []);
            foreach (['obstructions','noise_restrictions','client_constraints','programme_constraints'] as $k) {
                if (! empty(trim((string) ($cons[$k] ?? '')))) return false;
            }
            $so = (array) ($room['signoff'] ?? []);
            if (! empty($so['engineer_name']) || ! empty($so['engineer_confirmed'])) return false;
        }

        return true;
    }

    /**
     * Group quote equipment rows by their area (room) name, keyed by a
     * lowercased/trimmed area so case/whitespace variance collapses to the
     * same room. Each group preserves quote insertion order.
     *
     * @param  array<int, array<string, mixed>>  $equipment
     * @return array<string, array<int, array{name: string, quantity: int}>>
     */
    private function groupEquipmentByRoom(array $equipment): array
    {
        $grouped = [];
        foreach ($equipment as $item) {
            if (! is_array($item)) continue;
            $area = trim((string) ($item['area'] ?? ''));
            if ($area === '') continue;
            $name = trim((string) ($item['name'] ?? ''));
            if ($name === '') continue;
            $qty  = max(1, (int) ($item['quantity'] ?? 1));
            $key  = strtolower($area);
            $grouped[$key][] = ['name' => $name, 'quantity' => $qty];
        }
        return $grouped;
    }

    /**
     * Render a deterministic kit string for a room — one `"{qty} × {name}"`
     * entry per line, in quote order. Returns '' when the room has no
     * itemised equipment in the grouped map.
     *
     * @param  array<string, array<int, array{name: string, quantity: int}>>  $grouped
     */
    private function kitListForRoom(string $roomName, array $grouped): string
    {
        $key   = strtolower(trim($roomName));
        $items = $grouped[$key] ?? [];
        if (empty($items)) return '';

        return implode("\n", array_map(
            fn (array $i): string => $i['quantity'] . ' × ' . $i['name'],
            $items,
        ));
    }

    /**
     * Archive (supersede) a survey by stamping superseded_at = now().
     *
     * Called atomically within the DB::transaction in create() and
     * createFromProject() so old survey is archived and new survey is created
     * in the same transaction — either both succeed or neither does.
     */
    private function supersedeSurvey(SiteSurvey $survey): void
    {
        $survey->update(['superseded_at' => now()]);

        Log::info('SurveyService: survey superseded', [
            'survey_id'  => $survey->id,
            'project_id' => $survey->project_id,
        ]);
    }

    /**
     * Drop fully-empty rows from the cable_routes JSON array submitted from the
     * dynamic Alpine row-add UI. A row is considered empty when category, from,
     * to, length_m AND notes are all blank/null. Returns null if no real rows
     * remain so the column stays NULL rather than storing an empty array.
     *
     * Quick task 260503-rgg.
     *
     * @param  array<int, array<string, mixed>>|null  $rows
     */
    private function normalizeCableRoutes(?array $rows): ?array
    {
        if ($rows === null) {
            return null;
        }
        $clean = array_values(array_filter($rows, function ($r) {
            if (! is_array($r)) {
                return false;
            }
            $hasContent = trim((string) ($r['category'] ?? '')) !== ''
                || trim((string) ($r['from']     ?? '')) !== ''
                || trim((string) ($r['to']       ?? '')) !== ''
                || trim((string) ($r['notes']    ?? '')) !== ''
                || (($r['length_m'] ?? null) !== null && $r['length_m'] !== '');
            return $hasContent;
        }));
        return $clean === [] ? null : $clean;
    }

    /**
     * Same empty-row-strip logic for brackets_required. A row is empty when
     * equipment, model AND notes are all blank.
     *
     * Quick task 260503-rgg.
     *
     * @param  array<int, array<string, mixed>>|null  $rows
     */
    private function normalizeBracketRows(?array $rows): ?array
    {
        if ($rows === null) {
            return null;
        }
        $clean = array_values(array_filter($rows, function ($r) {
            if (! is_array($r)) {
                return false;
            }
            return trim((string) ($r['equipment'] ?? '')) !== ''
                || trim((string) ($r['model']     ?? '')) !== ''
                || trim((string) ($r['notes']     ?? '')) !== '';
        }));
        return $clean === [] ? null : $clean;
    }
}
