<?php

namespace App\Services\Drawings;

/**
 * Phase 17 — Pure D2 DSL emitter. Deterministic, no I/O, no AI.
 *
 * Direction enforcement: cable arrows derive from Device::signal_role classification
 * (loaded into adjacency rows by DrawingDataResolverService). Cables touching a
 * device with signal_role=null OR connecting two processors render as undirected
 * lines (CRIT-05).
 *
 * Label safety (T-17.02-01 / Warning 7): sanitiseLabel() escapes the FULL D2 DSL
 * meta-character set so a crafted equipment name from a QuoteWerks import cannot
 * inject D2 directives. See sanitiseLabel() docblock for the exact escape table.
 *
 * No AI calls. No Eloquent. No filesystem. Hand the same adjacency array to
 * build() twice and you get the same source string twice.
 *
 * @see app/Services/Drawings/SchematicGeneratorService.php — orchestrator that calls this builder.
 * @see app/Services/Drawings/DrawingDataResolverService.php — produces the input shape.
 */
class SchematicD2SourceBuilder
{
    /**
     * Allowlist mapping common name fragments to symbol-pack filenames. The
     * lookup order is "first-match-wins" — so order matters. Keys are
     * lowercase fragments expected to appear in `equipment.name`.
     *
     * Unknown names fall back to a role-based default in resolveSymbol().
     *
     * @var array<string, string>
     */
    private const SYMBOL_ALIASES = [
        'projector' => 'projector.svg',
        'display' => 'display.svg',
        'tv' => 'display.svg',
        'screen' => 'display.svg',
        'monitor' => 'display.svg',
        'speaker' => 'speaker.svg',
        'microphone' => 'microphone.svg',
        'mic' => 'microphone.svg',
        'camera' => 'camera.svg',
        'ptz' => 'camera.svg',
        'switcher' => 'switcher.svg',
        'matrix' => 'switcher.svg',
        'dsp' => 'dsp.svg',
        'amplifier' => 'amplifier.svg',
        'amp' => 'amplifier.svg',
        'codec' => 'codec.svg',
        'control processor' => 'control-processor.svg',
        'control system' => 'control-processor.svg',
        'touch panel' => 'touch-panel.svg',
        'tsw' => 'touch-panel.svg',
        'byod' => 'byod-dongle.svg',
        'dongle' => 'byod-dongle.svg',
        'clickshare' => 'clickshare.svg',
        'mersive' => 'clickshare.svg',
        'network switch' => 'network-switch.svg',
        'poe switch' => 'network-switch.svg',
        'usb hub' => 'usb-hub.svg',
        'pc' => 'source-pc.svg',
        'desktop' => 'source-pc.svg',
        'laptop' => 'laptop.svg',
        'pdu' => 'pdu.svg',
        'rack' => 'equipment-rack.svg',
        'blanking' => 'blanking-panel.svg',
    ];

    public function __construct(private readonly array $config) {}

    /**
     * Build a complete D2 source document for a single room.
     *
     * @param  array{room_id:int|null,room_name:string,devices:array,cables:array}  $room
     * @return array{source:string, warnings:list<string>, ambiguous_cables:int}
     */
    public function build(array $room): array
    {
        $roomName = (string) ($room['room_name'] ?? '');
        $devices = (array) ($room['devices'] ?? []);
        $cables = (array) ($room['cables'] ?? []);

        $signalColours = (array) ($this->config['signal_colours'] ?? []);
        $symbolPack = (string) ($this->config['symbol_pack_path'] ?? '');

        $lines = [];
        $warnings = [];
        $ambiguous = 0;

        // ── Header ────────────────────────────────────────────────────────
        $lines[] = '# Auto-generated by SchematicD2SourceBuilder. Do not edit by hand.';
        $lines[] = '# Direction: source → destination, left-to-right (AVIXA convention).';
        $lines[] = 'direction: right';
        $lines[] = 'title: "'.$this->sanitiseLabel('Signal Flow — '.$roomName).'"';
        $lines[] = '';

        // ── Per-device nodes ──────────────────────────────────────────────
        // Index devices by sanitised id so the cable loop can look them up
        // for direction inference.
        $deviceIndex = [];
        foreach ($devices as $device) {
            $rawId = (string) ($device['equipment_id'] ?? '');
            if ($rawId === '') {
                continue;
            }
            $nodeId = $this->sanitiseIdentifier($rawId);
            $deviceIndex[$rawId] = [
                'node_id' => $nodeId,
                'role' => $device['signal_role'] ?? null,
                'name' => (string) ($device['name'] ?? ''),
            ];

            // Three-line label: Manufacturer / generic name / model — same
            // convention real-world AV schematics use (e.g. "Crestron / Receiver
            // / AM-3200-GV"). Sanitise EACH PART individually first
            // (sanitiseLabel collapses control chars including \n), then join
            // with literal \n which D2's double-quoted parser renders as a
            // line break.
            $manufacturer = $this->sanitiseLabel((string) ($device['manufacturer'] ?? ''));
            $name = $this->sanitiseLabel((string) ($device['name'] ?? ''));
            $model = $this->sanitiseLabel((string) ($device['model'] ?? ''));
            $labelParts = array_values(array_filter(
                [trim($manufacturer), trim($name), trim($model)],
                fn (string $p) => $p !== ''
            ));
            $label = $labelParts ? implode('\n', $labelParts) : $this->sanitiseLabel($rawId);

            $symbol = $this->resolveSymbol((string) ($device['name'] ?? ''), $device['signal_role'] ?? null);
            $iconPath = rtrim($symbolPack, '/\\').DIRECTORY_SEPARATOR.$symbol;
            // D2 v0.7 resolves `icon:` paths via its bundler. The bundler prepends
            // the .d2 source file's directory to anything that looks like a relative
            // path AND incorrectly handles `file://` URIs by treating them as
            // relative — so we emit the plain absolute filesystem path with
            // forward slashes (cross-platform safe).
            $iconUri = str_replace('\\', '/', $iconPath);

            $lines[] = $nodeId.': "'.$label.'" {';
            $lines[] = '  shape: image';
            $lines[] = '  icon: '.$iconUri;
            $lines[] = '}';
        }
        $lines[] = '';

        // ── Per-cable edges ───────────────────────────────────────────────
        foreach ($cables as $cable) {
            $cableId = (string) ($cable['cable_id'] ?? '');
            $sourceId = $cable['source_equipment_id'] ?? null;
            $destId = $cable['dest_equipment_id'] ?? null;
            $sourcePort = (string) ($cable['source_port'] ?? '');
            $destPort = (string) ($cable['dest_port'] ?? '');
            $signalType = (string) ($cable['signal_type'] ?? 'unknown');

            if ($sourceId === null || $destId === null) {
                $warnings[] = sprintf(
                    'Cable %s skipped — missing source/destination equipment id',
                    $cableId !== '' ? $cableId : '(unnamed)'
                );

                continue;
            }

            $sourceKey = (string) $sourceId;
            $destKey = (string) $destId;

            // Direction enforcement (CRIT-05): consult device classification.
            // Source must be ROLE_SOURCE AND destination must be ROLE_DESTINATION;
            // if either side is null OR both are processors, render undirected.
            $srcRole = $deviceIndex[$sourceKey]['role'] ?? null;
            $dstRole = $deviceIndex[$destKey]['role'] ?? null;

            $directed = (
                $srcRole === \App\Models\Device::ROLE_SOURCE
                && $dstRole === \App\Models\Device::ROLE_DESTINATION
            ) || (
                // Source emitting through a processor stays directed too
                // (sources / processors flow forward; only NULL is ambiguous).
                $srcRole !== null && $dstRole !== null
                && ! ($srcRole === \App\Models\Device::ROLE_PROCESSOR && $dstRole === \App\Models\Device::ROLE_PROCESSOR)
                && ! ($srcRole === \App\Models\Device::ROLE_DESTINATION)
                && ! ($dstRole === \App\Models\Device::ROLE_SOURCE)
            );

            if (! $directed) {
                $ambiguous++;
                $warnings[] = sprintf(
                    'Cable %s renders undirected — ambiguous direction (src role=%s, dst role=%s)',
                    $cableId !== '' ? $cableId : '(unnamed)',
                    $srcRole ?? 'null',
                    $dstRole ?? 'null'
                );
            }

            $arrow = $directed ? '->' : '--';

            // Resolve node ids, falling back to a sanitised raw key when the
            // device wasn't in the equipment list (orphan cable referencing
            // an external connector). This keeps the schematic complete
            // instead of silently dropping the edge.
            $srcNode = $deviceIndex[$sourceKey]['node_id'] ?? $this->sanitiseIdentifier($sourceKey);
            $dstNode = $deviceIndex[$destKey]['node_id'] ?? $this->sanitiseIdentifier($destKey);

            $portLabel = '';
            if ($sourcePort !== '' || $destPort !== '') {
                $portLabel = sprintf(' (%s → %s)', $sourcePort, $destPort);
            }
            $edgeLabel = $this->sanitiseLabel(($cableId !== '' ? $cableId : 'cable').$portLabel);

            $colour = (string) ($signalColours[$signalType] ?? $signalColours['unknown'] ?? '#000000');

            $lines[] = sprintf(
                '%s %s %s: "%s" {',
                $srcNode,
                $arrow,
                $dstNode,
                $edgeLabel
            );
            $lines[] = sprintf('  style.stroke: "%s"', $colour);
            if ($signalType === 'power') {
                $lines[] = '  style.stroke-dash: 4';
            }
            $lines[] = '}';
        }

        return [
            'source' => implode("\n", $lines)."\n",
            'warnings' => $warnings,
            'ambiguous_cables' => $ambiguous,
        ];
    }

    /**
     * Public so the test suite can exercise it in isolation (Warning 7
     * crafted-name test).
     *
     * D2 DSL meta characters that MUST be escaped when inlining a string into
     * a double-quoted D2 label:
     *   1. Backslash         \    → \\
     *   2. Double-quote      "    → \"
     *   3. Backtick          `    → \`        (D2 supports raw-string blocks delimited by backticks)
     *   4. Newline / CR      \n   → space     (multi-line strings use a different delimiter; collapse to space)
     *   5. Other control     0x00–0x1F → space (avoids smuggling NULs / VT into the source file)
     *
     * Order matters: escape backslash FIRST, then double-quote, then backtick.
     * Otherwise the backslash escape will double-escape the others.
     *
     * Note on `$`: D2 v0.7.1 does NOT perform shell-style `$var` interpolation
     * inside double-quoted labels — interpolation lives in `vars: { ... }`
     * blocks at document level. No escape needed for `$`.
     */
    public function sanitiseLabel(string $raw): string
    {
        // 1. Strip control characters (0x00–0x1F) — collapses newlines too.
        $clean = preg_replace('/[\x00-\x1F]/u', ' ', $raw) ?? '';
        // 2. Order matters: backslash FIRST, otherwise it double-escapes the next two.
        $clean = str_replace('\\', '\\\\', $clean);
        // 3. Double-quote.
        $clean = str_replace('"', '\\"', $clean);
        // 4. Backtick (D2 raw-string delimiter — escape so labels can never open one).
        $clean = str_replace('`', '\\`', $clean);

        return $clean;
    }

    /**
     * Reduce an arbitrary equipment_id string to a D2-safe identifier.
     * D2 identifiers tolerate alphanumerics + underscore; everything else
     * gets squashed.
     */
    private function sanitiseIdentifier(string $raw): string
    {
        $safe = preg_replace('/[^a-zA-Z0-9_]/', '_', $raw) ?? '';
        if ($safe === '' || preg_match('/^[0-9]/', $safe)) {
            $safe = 'eq_'.$safe;
        }

        return $safe;
    }

    /**
     * Map an equipment name + optional signal_role to a symbol filename.
     * Order: name-fragment allowlist → role-based default → generic-source.
     */
    private function resolveSymbol(string $name, ?string $role): string
    {
        $needle = strtolower($name);
        foreach (self::SYMBOL_ALIASES as $fragment => $filename) {
            if ($fragment !== '' && str_contains($needle, $fragment)) {
                return $filename;
            }
        }

        return match ($role) {
            \App\Models\Device::ROLE_SOURCE => 'generic-source.svg',
            \App\Models\Device::ROLE_DESTINATION => 'generic-destination.svg',
            \App\Models\Device::ROLE_PROCESSOR => 'switcher.svg',
            default => 'generic-source.svg',
        };
    }
}
