<?php

namespace App\Services;

use App\Core\AI\AIManager;
use App\Core\AI\Prompts\MethodStatementPrompt;
use App\Exceptions\AIGenerationException;
use Illuminate\Support\Facades\Log;

/**
 * Generates method statement phases via a lean AI prompt.
 *
 * The AI only generates the phase titles and step descriptions.
 * All other RAMS content (hazards, PPE, persons at risk) is produced
 * locally by RamsBuilderService — no AI is used for those sections.
 *
 * Falls back to a static five-phase template when:
 *   - The AI provider is unavailable or returns an error.
 *   - The AI response cannot be decoded into a valid phases array.
 *   - All decoded phases fail normalisation (missing title or empty steps).
 *
 * The static fallback guarantees RAMS generation always completes.
 */
class MethodStatementService
{
    // =========================================================================
    // PUBLIC ENTRY POINT
    // =========================================================================

    /**
     * Generate method statement phases.
     *
     * @param  array  $parsedQuote  Output from QuoteParserService
     *                              (keys: client, site, ref, equipment, tasks, rooms)
     * @param  array  $classified   Output from EquipmentClassifierService
     *                              (keys: activities, categories, summary, ...)
     * @return array  ['phases' => [['title' => string, 'steps' => string[]], ...]]
     */
    public function generate(array $parsedQuote, array $classified, array $hazards = []): array
    {
        $equipmentSummary = $this->buildEquipmentSummary($parsedQuote);
        $hazardSummary    = $this->buildHazardSummary($hazards);
        $roomSummary      = $this->buildRoomOverviewSummary($parsedQuote);

        $context = [
            'site_address'  => $parsedQuote['site']      ?? 'the site',
            'scope_summary' => $this->buildScope($parsedQuote, $classified),
            'activities'    => $classified['activities'] ?? [],
            'rooms'         => $this->buildRoomList($parsedQuote),
            'equipment_summary' => $equipmentSummary,
            'hazard_summary'    => $hazardSummary,
            'room_overview_summaries' => $roomSummary,
        ];

        $prompt = (new MethodStatementPrompt())->withContext($context);

        try {
            $result     = AIManager::run($prompt, $context);
            $normalised = $this->normalise($result);

            if (! empty($normalised['phases'])) {
                Log::info('MethodStatementService: AI method statement generated', [
                    'phase_count' => count($normalised['phases']),
                ]);

                return $normalised;
            }

            Log::warning('MethodStatementService: AI returned empty or unusable phases, using static fallback.');
        } catch (AIGenerationException $e) {
            Log::warning('MethodStatementService: AI generation failed, using static fallback.', [
                'error' => $e->getMessage(),
            ]);
        }

        Log::info('MethodStatementService: returning static fallback method statement.');

        return $this->fallbackPhases();
    }

    // =========================================================================
    // PUBLIC FALLBACK
    // =========================================================================

    /**
     * Return the static fallback method statement directly.
     *
     * Called by MethodStatementGeneratorService when:
     *   - Low-confidence parse (confidence < 0.5) and AI must be skipped.
     *   - All content-validation retry attempts are exhausted.
     *
     * The optional $context parameter is accepted for future extensibility
     * but is not currently used — the fallback is always the same static template.
     */
    public function fallback(array $context = []): array
    {
        return $this->fallbackPhases();
    }

    // =========================================================================
    // PRIVATE HELPERS
    // =========================================================================

    /**
     * Build a concise scope summary for the AI prompt from parsed quote data.
     *
     * Priority:
     *   1. scope_of_works (human-reviewed or auto-generated) — most specific
     *   2. tasks extracted from quote
     *   3. classifier human-readable summary
     *   4. equipment summary
     *   5. generic fallback
     */
    private function buildScope(array $parsed, array $classified): string
    {
        // Prefer the human-reviewed scope_of_works paragraph when available.
        // This is pre-generated by ExtractQuoteJob or the user via the review form.
        $scope = trim((string) ($parsed['scope_of_works'] ?? ''));
        if ($scope !== '') {
            return $scope;
        }

        // Prefer tasks extracted from the quote (most specific)
        if (! empty($parsed['tasks'])) {
            $tasks = array_slice($parsed['tasks'], 0, 5);
            return implode('; ', $tasks);
        }

        // Fall back to the classifier's human-readable equipment summary
        if (! empty($classified['summary'])) {
            return $classified['summary'];
        }

        $equip = $this->buildEquipmentSummary($parsed);
        if ($equip !== '') {
            return $equip;
        }

        return 'AV installation works as per quotation';
    }

    /**
     * Build a short, concrete equipment summary from parsed quote items.
     */
    private function buildEquipmentSummary(array $parsed): string
    {
        $items = (array) ($parsed['equipment'] ?? []);
        if (empty($items)) {
            return '';
        }

        $parts = [];
        foreach (array_slice($items, 0, 5) as $item) {
            $qty  = (int) ($item['qty'] ?? 1);
            $desc = trim((string) ($item['description'] ?? ''));
            if ($desc === '') {
                continue;
            }
            $parts[] = ($qty > 0 ? $qty . '× ' : '') . $desc;
        }

        return implode('; ', $parts);
    }

    /**
     * Build a compact hazard summary for the prompt.
     */
    private function buildHazardSummary(array $hazards): string
    {
        $labels = array_values(array_filter(
            array_map(
                static fn ($h): string => is_array($h) ? (string) ($h['hazard'] ?? '') : (string) $h,
                $hazards
            ),
            static fn (string $s): bool => $s !== '',
        ));

        if (empty($labels)) {
            return '';
        }

        return implode(', ', array_slice($labels, 0, 6));
    }

    /**
     * Build a compact room summary list for the prompt.
     * Includes solution type name and install method steps where available.
     */
    private function buildRoomOverviewSummary(array $parsed): string
    {
        $rows = array_filter(
            (array) ($parsed['room_overviews'] ?? []),
            static fn ($r): bool => is_array($r) && trim((string) ($r['room'] ?? '')) !== ''
        );

        if (empty($rows)) {
            return '';
        }

        // Pre-load all referenced solution types in one query.
        $solutionTypeIds = array_filter(array_unique(array_map(
            fn ($r) => (int) ($r['solution_type_id'] ?? 0),
            $rows
        )));
        $solutionTypes = [];
        if (! empty($solutionTypeIds)) {
            foreach (\App\Models\SolutionType::whereIn('id', $solutionTypeIds)->get() as $st) {
                $solutionTypes[$st->id] = $st;
            }
        }

        $parts = [];
        foreach ($rows as $row) {
            $room     = trim((string) ($row['room']          ?? ''));
            $summary  = trim((string) ($row['works_summary'] ?? $row['summary'] ?? ''));
            $overview = trim((string) ($row['overview']      ?? ''));

            if ($room === '') {
                continue;
            }

            // Build the line: "Room [Solution Type]: summary/overview"
            $stId  = (int) ($row['solution_type_id'] ?? 0);
            $st    = $stId ? ($solutionTypes[$stId] ?? null) : null;
            $label = $st ? "{$room} [{$st->name}]" : $room;

            if ($summary === '' && $overview !== '') {
                $summary = $this->firstSentence($overview);
            }

            // If a solution type has install_method, append abbreviated steps as context
            $methodNote = '';
            if ($st && $st->install_method) {
                $steps = $st->methodLines();
                // Include first 3 steps as a brief hint
                $abbreviated = array_slice($steps, 0, 3);
                $methodNote  = ' [Install: ' . implode('; ', $abbreviated) . ']';
            }

            if ($summary === '' && $methodNote === '') {
                continue;
            }

            $parts[] = "{$label}: {$summary}{$methodNote}";
        }

        return $parts ? implode("\n", $parts) : '';
    }

    /**
     * Prefer rooms with overview/summary text to avoid generic placeholders.
     */
    private function buildRoomList(array $parsed): array
    {
        $rows = array_filter(
            (array) ($parsed['room_overviews'] ?? []),
            static fn ($r): bool => is_array($r) && trim((string) ($r['room'] ?? '')) !== ''
        );

        $rooms = [];
        foreach ($rows as $row) {
            $room = trim((string) ($row['room'] ?? ''));
            $overview = trim((string) ($row['overview'] ?? ''));
            $summary = trim((string) ($row['summary'] ?? ''));
            if ($room === '') {
                continue;
            }
            if ($overview === '' && $summary === '') {
                continue;
            }
            $rooms[] = $room;
        }

        if (! empty($rooms)) {
            return array_values(array_unique($rooms));
        }

        return array_values(array_filter(
            array_map('strval', (array) ($parsed['rooms'] ?? [])),
            static fn (string $s): bool => trim($s) !== ''
        ));
    }

    /**
     * Extract a short first-sentence summary.
     */
    private function firstSentence(string $text): string
    {
        $text = trim($text);
        if ($text === '') {
            return '';
        }

        $sentence = preg_split('/(?<=[.!?])\s+/', $text)[0] ?? $text;
        $sentence = trim($sentence);

        return mb_strlen($sentence) > 220 ? mb_substr($sentence, 0, 220) . '…' : $sentence;
    }

    /**
     * Normalise the raw AI response into the expected phases array format.
     *
     * Drops individual phases that have no title or no usable steps.
     * Returns ['phases' => []] when nothing valid remains — the caller treats
     * this as a signal to use the static fallback.
     */
    private function normalise(array $result): array
    {
        $phases = $result['phases'] ?? [];

        if (empty($phases) || ! is_array($phases)) {
            return ['phases' => []];
        }

        $normalised = [];

        foreach ($phases as $phase) {
            if (! is_array($phase)) {
                continue;
            }

            $title = trim((string) ($phase['title'] ?? ''));
            $steps = array_values(array_filter(
                array_map('strval', (array) ($phase['steps'] ?? [])),
                static fn (string $s): bool => strlen(trim($s)) > 3,
            ));

            if ($title === '' || empty($steps)) {
                continue;
            }

            $normalised[] = [
                'title' => $title,
                'steps' => $steps,
            ];
        }

        return ['phases' => $normalised];
    }

    /**
     * Static fallback method statement used when the AI is unavailable or returns
     * an unusable response. Uses generic AV installation language — no brand references.
     */
    private function fallbackPhases(): array
    {
        return [
            'phases' => [
                [
                    'title' => '1. Pre-Start Checks',
                    'steps' => [
                        'Hold a toolbox talk and brief all operatives on the RAMS, scope, and site constraints before starting work.',
                        'Complete site induction, confirm the emergency assembly point, and agree room-by-room sequencing to minimise disruption.',
                        'Check the asbestos register or survey before any drilling or ceiling access is undertaken.',
                        'Confirm permit-to-work requirements for ceiling access, electrical isolation, or hot works with building management.',
                        'Coordinate with the client IT and facilities teams to confirm network access requirements, room booking arrangements, and any constraints on working hours.',
                    ],
                ],
                [
                    'title' => '2. Delivery and Materials Handling',
                    'steps' => [
                        'Confirm delivery vehicle access, parking or loading bay arrangements, and agreed delivery time with the site contact.',
                        'Verify goods lift availability and suitability for large display and equipment packaging, and agree a contingency if lift access is unavailable.',
                        'Offload and move equipment using suitable trolleys and team lifts, keeping routes clear and protecting floor and wall finishes.',
                        'Log all delivered items against the delivery note and raise any shortages or damages with the project manager before installation begins.',
                    ],
                ],
                [
                    'title' => '3. Access Equipment Setup',
                    'steps' => [
                        'Select access equipment appropriate to the task and confirm maximum working height limits before use.',
                        'Ensure operatives using platforms or towers are competent and trained (e.g., PASMA or WAH training where required).',
                        'Establish a work-at-height rescue plan and brief all team members before commencing overhead works.',
                        'Set exclusion zones and signage around overhead work areas and maintain three points of contact while working at height.',
                    ],
                ],
                [
                    'title' => '4. Installation Works',
                    'steps' => [
                        'Sequence installation by room in the agreed order, completing containment, mounting and cabling in each area before moving on.',
                        'Route cables via the agreed containment (ceiling void, trunking or conduit as per survey), fire-stop all penetrations, and segregate data, audio and power runs.',
                        'Survey wall substrates, select fixings appropriate to the surface type, and mount displays and screens using two-person lifts, torquing fixings to manufacturer guidance.',
                        'Install audio equipment including speakers and amplifiers using approved structural fixings, routing cables neatly back to equipment locations.',
                        'Build rack infrastructure from the bottom up to manage weight distribution and install equipment to manufacturer specifications, without disrupting any live infrastructure.',
                        'Connect control and switching equipment, apply labelling to all interfaces, and verify signal flow before proceeding to commissioning.',
                    ],
                ],
                [
                    'title' => '5. Testing and Commissioning',
                    'steps' => [
                        'Terminate and label all cables using the agreed convention (e.g., room code and port number) at both ends.',
                        'Confirm all test equipment calibration is current and record test results for inclusion in the handover pack.',
                        'Power up systems in sequence, verify signal paths, and confirm audio, video and control functionality in each room.',
                        'Carry out control system programming and test all user-facing functions including source switching, volume control, and display operation.',
                        'Address any faults identified during commissioning and re-test to confirm resolution before proceeding to handover.',
                    ],
                ],
                [
                    'title' => '6. Final Checks and Handover',
                    'steps' => [
                        'Remove all access equipment, barriers, packaging and waste from work areas and leave the site clean and tidy.',
                        'Provide end-user training to the client team on system operation, covering day-to-day use and basic fault diagnosis.',
                        'Carry out a snagging walkthrough, log any defects, and agree a close-out plan before final sign-off.',
                        'Hand over as-built documentation, test results, and commissioning records to the client representative.',
                    ],
                ],
            ],
        ];
    }
}
