<?php

namespace Database\Seeders;

use App\Models\SolutionType;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class SolutionTypeSeeder extends Seeder
{
    public function run(): void
    {
        $types = [

            // ── 1. Video Conferencing ─────────────────────────────────────────
            [
                'name'        => 'Video Conferencing',
                'description' => 'Teams / Zoom / Cisco room — camera, codec, display, microphone and speaker system for hybrid meetings.',
                'survey_checklist' => implode("\n", [
                    'Room dimensions (W × D × H) — determine display size and camera FOV',
                    'Seating capacity and table configuration (boardroom, U-shape, theatre)',
                    'UC platform in use — Microsoft Teams, Zoom, Cisco Webex, Google Meet',
                    'Existing AV/VC equipment to retain or remove',
                    'Main display position — wall, floor stand, ceiling drop?',
                    'Camera mount position — on display, wall, ceiling?',
                    'Sightline check — can all seats see the display clearly?',
                    'Microphone coverage — ceiling, table or bar mic? Any dead zones?',
                    'Speaker positions — bar below display, ceiling, or existing PA?',
                    'Power outlets near display, table and rack position',
                    'Network ports — quantity and location; PoE availability',
                    'Cable containment route from display to AV rack',
                    'Wall material at display position (plasterboard, brick, glass)',
                    'Ceiling type (suspended, concrete) for cable routing',
                    'Lighting conditions — glare on display from windows?',
                    'Existing HDMI/USB/cable infrastructure to reuse',
                    'AV rack/credenza location and ventilation',
                    'Control system requirement (touch panel, tablet, wall plate)',
                ]),
                'install_method' => implode("\n", [
                    '1. First fix — install cable containment (trunking/conduit), pull AV, USB, network and power cables to all device positions',
                    '2. Mount display bracket to wall; verify wall construction and use appropriate fixings',
                    '3. Install display; dress and terminate all cables at display',
                    '4. Mount camera above or below display; connect USB/HDMI/IP as required',
                    '5. Install microphone (ceiling tiles cut, table grommets, or bar unit positioned)',
                    '6. Build and rack-mount AV equipment — codec, switcher, amplifier, power conditioning',
                    '7. Install control system touch panel or wall plate',
                    '8. Network: connect codec and control system to client IT infrastructure; configure VLANs if required',
                    '9. Power-on and configure codec — enrol device to UC platform tenant',
                    '10. Test: camera framing, microphone coverage, speaker levels, content sharing (HDMI/wireless)',
                    '11. Full end-to-end call test with remote participant',
                    '12. Label all cables; update as-built drawing; user handover',
                ]),
                'sort_order' => 1,
            ],

            // ── 2. Hybrid Meeting Room ────────────────────────────────────────
            [
                'name'        => 'Hybrid Meeting Room',
                'description' => 'Smaller huddle/meeting space optimised for hybrid working — all-in-one bar unit or compact codec with wireless presentation.',
                'survey_checklist' => implode("\n", [
                    'Room capacity (typically 4–8 persons)',
                    'UC platform — Teams, Zoom, or agnostic',
                    'Display size — wall-mounted or existing screen?',
                    'All-in-one bar unit (ClickShare, Neat Bar, Logitech Rally Bar) vs separate components',
                    'Power outlet at display wall for bar unit',
                    'Network/PoE port at display position',
                    'BYOD or dedicated room system?',
                    'Wireless presentation required (ClickShare, AirPlay, Miracast)?',
                    'Existing furniture — table style, seating plan',
                    'Cable route from display to any table connectivity box',
                    'Lighting and glare assessment',
                ]),
                'install_method' => implode("\n", [
                    '1. First fix — pull power and data cables to display and table positions',
                    '2. Mount display bracket; fit and terminate display',
                    '3. Mount all-in-one bar unit below/above display; connect power and network',
                    '4. Install table connectivity box (HDMI, USB-C, power) if required',
                    '5. Enrol device to UC platform; configure meeting room account',
                    '6. Configure wireless presentation unit if included',
                    '7. Test call, sharing and audio — adjust camera framing and mic sensitivity',
                    '8. User handover and labelling',
                ]),
                'sort_order' => 2,
            ],

            // ── 3. Digital Signage ────────────────────────────────────────────
            [
                'name'        => 'Digital Signage',
                'description' => 'Single or multi-display signage — commercial displays, media players and CMS-driven content.',
                'survey_checklist' => implode("\n", [
                    'Display location — wall, portrait or landscape, freestanding?',
                    'Wall construction at mount position (stud, masonry, glass, partition)',
                    'Display size and viewing distance — minimum 6× display height for comfortable reading',
                    'Ambient light levels — direct sunlight? High-brightness display needed?',
                    'Power outlet proximity or new spur required',
                    'Network/data connection — wired Ethernet or WiFi?',
                    'Content source — local media player, CMS network player, built-in SoC?',
                    'CMS platform in use or to be recommended',
                    'Cable route — through wall, trunking or surface mounted',
                    'Fire/planning considerations for large format or double-sided units',
                    'Bracket type — fixed, tilt or VESA specification',
                    'Interactivity required (touch overlay)?',
                ]),
                'install_method' => implode("\n", [
                    '1. First fix — install cable containment; pull power and data cables to display position',
                    '2. Mark and fix wall bracket using appropriate fixings for wall construction',
                    '3. Hang display and secure; cable dress and connection at rear',
                    '4. Install and connect media player / SoC configuration',
                    '5. Connect to network; configure IP settings',
                    '6. Enrol display in CMS; assign content schedule',
                    '7. Test display orientation, content playback and auto on/off schedule',
                    '8. Label and photograph installation; update asset register',
                ]),
                'sort_order' => 3,
            ],

            // ── 4. PA / Sound System ──────────────────────────────────────────
            [
                'name'        => 'PA / Sound System',
                'description' => 'Background music, paging and public address — ceiling or surface-mount speakers, amplifiers, DSP and source inputs.',
                'survey_checklist' => implode("\n", [
                    'Room dimensions and volume — determine speaker quantity and spacing',
                    'Ceiling type — suspended grid (easy), plasterboard, concrete, open truss',
                    'Ceiling height — affects speaker SPL and coverage angle selection',
                    'Background noise level estimate (open plan office, plant room, reception)',
                    'Number of audio zones required',
                    'Source inputs required — microphone, line-level, streaming, telephone paging',
                    'Emergency voice alarm (EVA) or fire alarm integration required?',
                    'Existing speaker positions and wiring to reuse',
                    'Amplifier and DSP rack location',
                    'Cable route from amp rack to all speaker positions',
                    'Volume control positions in each zone',
                    'AV rack power supply and ventilation',
                    'Client music source (Spotify, DAB, local playlist)',
                ]),
                'install_method' => implode("\n", [
                    '1. Mark out speaker positions per coverage design (typically 1× ceiling height spacing)',
                    '2. First fix — pull 2-core 1.5mm speaker cable from amp position to each speaker drop',
                    '3. Install cable containment above ceiling/in roof void',
                    '4. Cut ceiling tiles or drill penetrations for speaker backboxes',
                    '5. Fit speaker backboxes or brackets',
                    '6. Install and terminate amplifier, DSP and source equipment in rack',
                    '7. Connect and label all speaker runs at amplifier/DSP outputs',
                    '8. Install zone volume controls and input plates at designated positions',
                    '9. Power-on and configure DSP — EQ, routing, input gain, zone levels',
                    '10. Acoustic test — measure SPL in each zone; adjust EQ and levels',
                    '11. Test paging mic, all sources and zone independence',
                    '12. User handover; provide DSP backup file',
                ]),
                'sort_order' => 4,
            ],

            // ── 5. LED Video Wall ─────────────────────────────────────────────
            [
                'name'        => 'LED Video Wall',
                'description' => 'Direct-view LED panels — fine pitch indoor or outdoor LED wall with video processor.',
                'survey_checklist' => implode("\n", [
                    'Available wall area (W × H) and target display size',
                    'Wall construction — must support significant weight (LED cabinets 10–25 kg/m²)',
                    'Floor-standing or wall-mounted structure?',
                    'Floor loading assessment if large or multi-tier installation',
                    'Pixel pitch selection — viewing distance (minimum 1× PP in metres = min viewing distance in mm)',
                    'Ambient light levels — brightness (nits) specification',
                    'Power requirements — total draw, phase availability, UPS requirement',
                    'Cable routes for power and data from processor to wall',
                    'Video processor location and signal source inputs',
                    'Rear service access or front-service cabinets required?',
                    'Control room / operator position',
                    'Cooling and ventilation in the space',
                    'Network connection for remote monitoring/control',
                    'Structural engineer sign-off required?',
                ]),
                'install_method' => implode("\n", [
                    '1. Structural assessment and approval for wall or floor-standing frame',
                    '2. Fabricate and install steel subframe structure; level and plumb',
                    '3. First fix — install power distribution boards and data cabling to frame',
                    '4. Mount LED cabinets row by row from bottom; level each row',
                    '5. Connect inter-cabinet data and power looms',
                    '6. Install and rack video processor; connect signal sources',
                    '7. Run main data link from processor to first cabinet',
                    '8. Power-on; configure video processor resolution and mapping',
                    '9. Cabinet calibration — uniformity, brightness and colour correction using manufacturer software',
                    '10. Test all content inputs and signal distribution',
                    '11. Install any facade trims or bezels',
                    '12. Hand over processor files and calibration data; train operator',
                ]),
                'sort_order' => 5,
            ],

            // ── 6. LCD Video Wall ─────────────────────────────────────────────
            [
                'name'        => 'LCD Video Wall',
                'description' => 'Ultra-narrow bezel LCD panel array — typically 2×2 to 6×4 configurations with video wall controller.',
                'survey_checklist' => implode("\n", [
                    'Number of displays — rows × columns configuration',
                    'Display size (46", 49", 55") and bezel specification',
                    'Wall construction and fixing capability for combined weight',
                    'Floor space for service access (minimum 600mm front clearance)',
                    'Power outlets — one per display or shared spur',
                    'Video wall controller location and PC/media source inputs',
                    'Signal distribution method — fibre, Cat6 extenders, direct cabling',
                    'Control system for on/off scheduling',
                    'Existing cable containment or new trunking required',
                    'Landscape or portrait orientation of individual panels',
                    'Ambient light and glare assessment',
                ]),
                'install_method' => implode("\n", [
                    '1. Mark wall grid and fix primary mounting rail system; check level across full width',
                    '2. First fix — pull power and signal cables to each panel position',
                    '3. Install displays onto mounting system row by row; pixel-align bezels',
                    '4. Connect power and signal (DP/HDMI) cables to each display',
                    '5. Install video wall controller in rack; connect all signal outputs',
                    '6. Power-on; configure video wall controller — display layout, resolution, bezel compensation',
                    '7. Align and calibrate colour/brightness uniformity across panels',
                    '8. Test all input sources and switching',
                    '9. Configure scheduling/control system',
                    '10. Document configuration; train operator',
                ]),
                'sort_order' => 6,
            ],

            // ── 7. Interactive / Collaboration ────────────────────────────────
            [
                'name'        => 'Interactive / Collaboration',
                'description' => 'Interactive flat panel display (IFP) for collaborative working, teaching or design review.',
                'survey_checklist' => implode("\n", [
                    'Room type — classroom, training, design studio, boardroom',
                    'Display size (65", 75", 86", 98") — viewing distance and seating plan',
                    'Wall position — clear of windows, central sightline',
                    'Wall construction for bracket fixing',
                    'Mounting height — standing use (centre ~140cm AFF) or seated?',
                    'Existing whiteboard or projector screen to remove?',
                    'PC source — built-in OPS module, external PC, or BYOD?',
                    'USB-C / HDMI table connectivity required?',
                    'Wireless presentation required?',
                    'Power outlet at display wall position',
                    'Network port at display (for updates, remote management)',
                    'Cable route for any external PC or table box',
                    'Acoustic treatment if voice recognition / AI features used',
                ]),
                'install_method' => implode("\n", [
                    '1. Remove existing display, projector or whiteboard if required; make good wall',
                    '2. First fix — pull power, network and AV cables to display position',
                    '3. Install floor-standing bracket or wall bracket using correct fixings',
                    '4. Fit display; dress and terminate all cables',
                    '5. Install OPS/PC module if specified',
                    '6. Install wireless presentation unit if required',
                    '7. Install table connectivity box and cable management if specified',
                    '8. Power-on; configure display — input settings, touch calibration, OS setup',
                    '9. Install required apps and software; connect to WiFi/Ethernet',
                    '10. Test touch, stylus, wireless sharing and all inputs',
                    '11. User handover and training on interactive features',
                ]),
                'sort_order' => 7,
            ],

            // ── 8. Divisible / Twin Room ──────────────────────────────────────
            [
                'name'        => 'Divisible / Twin Room',
                'description' => 'Two rooms separated by a moveable partition wall that can operate independently or as one combined space.',
                'survey_checklist' => implode("\n", [
                    'Partition wall type — acoustic, operable, fixed?',
                    'Combined room dimensions vs individual room dimensions',
                    'AV requirement in each half independently',
                    'Combined mode AV requirement — linked displays, combined audio?',
                    'Display positions in each zone — avoid partition wall overlap',
                    'Audio zone independence — separate amps or DSP matrix routing',
                    'Microphone strategy — individual room or combined array?',
                    'Control system — single touch panel with mode switching or separate panels?',
                    'Partition sensor integration for automatic mode switching?',
                    'Cable containment — above partition or through dedicated conduit',
                    'Power supply to each zone independently',
                    'Network infrastructure for each room AV system',
                ]),
                'install_method' => implode("\n", [
                    '1. Survey both room halves and confirm partition line and operation',
                    '2. First fix — pull cables for each zone plus combined-mode spurs above ceiling void',
                    '3. Install displays, cameras, microphones and speakers in each zone as per individual room type',
                    '4. Install DSP / matrix switcher with independent zone outputs and combined bus',
                    '5. Install partition open/close sensor wiring if required',
                    '6. Commission each room independently — test AV in isolation',
                    '7. Configure DSP routing for combined mode — merge audio zones, extend video',
                    '8. Configure control system modes (Room A only / Room B only / Combined)',
                    '9. Test all three operating modes end-to-end',
                    '10. User handover — demonstrate mode switching procedure',
                ]),
                'sort_order' => 8,
            ],

            // ── 9. Audio Conferencing Only ────────────────────────────────────
            [
                'name'        => 'Audio Conferencing Only',
                'description' => 'Speakerphone or ceiling mic / speaker system for audio-only conference calls — no video.',
                'survey_checklist' => implode("\n", [
                    'Room size and seating capacity',
                    'UC/telephony platform — Teams Audio, Zoom Phone, traditional PSTN',
                    'Existing PSTN/IP phone infrastructure',
                    'Table configuration — determine speakerphone positioning',
                    'Ceiling mic preferred or table unit acceptable?',
                    'Existing network port at table or ceiling',
                    'Power at table position for speakerphone',
                    'Acoustic treatment — echo, reverberation issues?',
                    'Privacy/confidentiality requirement (sound masking?)',
                ]),
                'install_method' => implode("\n", [
                    '1. Install network outlet at table or ceiling mic position if not present',
                    '2. Pull power cable to table for speakerphone or PoE for ceiling unit',
                    '3. Install ceiling mic / speaker unit in tile or surface mount',
                    '4. Connect to network switch; configure PoE if required',
                    '5. Enrol device to UC platform; configure audio settings',
                    '6. Acoustic test — place call and verify coverage, echo cancellation, clarity',
                    '7. Label and document device IP/MAC for IT records',
                ]),
                'sort_order' => 9,
            ],

            // ── 10. Upgrade / Strip-out ───────────────────────────────────────
            [
                'name'        => 'Upgrade / Strip-out',
                'description' => 'Removal and replacement of legacy AV equipment — full or partial strip-out before new installation.',
                'survey_checklist' => implode("\n", [
                    'Full inventory of existing AV equipment (make, model, condition)',
                    'Items confirmed for removal — obtain written client approval',
                    'Items confirmed to retain and reuse',
                    'Existing cable infrastructure — reuse or replace?',
                    'Cable containment condition — trunking, conduit, ceiling voids',
                    'Wall/ceiling make-good required after removal?',
                    'Disposal method — client to arrange skip, or 21CAV to remove?',
                    'WEEE / data destruction requirements for removed equipment',
                    'Working hours restrictions — after hours strip-out required?',
                    'Access to ceiling voids and risers',
                    'Asbestos survey required (pre-1990 buildings)?',
                    'Photographs of existing installation for records',
                ]),
                'install_method' => implode("\n", [
                    '1. Photograph all existing equipment positions and cable routes before disconnection',
                    '2. Power-down and isolate all circuits — confirm with site electrician',
                    '3. Disconnect and remove displays, processors, racks — label or bag cables for client reference',
                    '4. Remove cable containment and pull all redundant cables',
                    '5. Make good wall/ceiling penetrations — fill, sand and paint to match where required',
                    '6. Remove and dispose of equipment in accordance with WEEE regulations',
                    '7. Site clean — remove all waste and packaging',
                    '8. Photo record of stripped space; sign-off with client before new install commences',
                    '9. Proceed with new installation as per separate solution type specification',
                ]),
                'sort_order' => 10,
            ],

            // ── 11. AV Infrastructure / Rack Build ────────────────────────────
            [
                'name'        => 'AV Infrastructure / Rack Build',
                'description' => 'Head-end rack build, cable infrastructure, patch panels and signal distribution for a multi-room system.',
                'survey_checklist' => implode("\n", [
                    'Rack room / IDF cupboard location and dimensions',
                    'Rack size required (6U, 12U, 22U, 42U)',
                    'Floor or wall-mount rack?',
                    'Ventilation and cooling in rack room',
                    'Dedicated AV power circuits — quantity, amperage',
                    'UPS requirement and runtime specification',
                    'Cable route from rack room to each room — floor, ceiling, risers',
                    'Conduit or trunking sizing for cable volume',
                    'Fibre or Cat6 for long-distance signal distribution',
                    'Existing IT patch panels / switch to integrate with',
                    'Remote monitoring / management requirement',
                    'Access control to rack room',
                ]),
                'install_method' => implode("\n", [
                    '1. Install rack enclosure; level and secure to floor or wall',
                    '2. Install power distribution unit (PDU), UPS and cable management',
                    '3. Pull all main trunk cables from rack room to each room end-point',
                    '4. Install patch panels and label all ports (patch schedule)',
                    '5. Rack-mount all head-end equipment — switcher, amplifier, processor, control system',
                    '6. Terminate and patch all cable runs; test continuity',
                    '7. Install network switch if AV-dedicated; configure VLANs',
                    '8. Power-on; configure all rack equipment',
                    '9. Test signal distribution to all rooms end-to-end',
                    '10. Install blanking panels; dress and cable-tie all internal rack cabling',
                    '11. Label all equipment; produce as-built rack elevation drawing',
                    '12. Remote monitoring / control system final configuration',
                ]),
                'sort_order' => 11,
            ],

            // ── 12. Lecture / Training Room ───────────────────────────────────
            [
                'name'        => 'Lecture / Training Room',
                'description' => 'Presentation-focused room — lecturer display, audience displays, podium PC, microphone and recording capability.',
                'survey_checklist' => implode("\n", [
                    'Room capacity and seating layout (theatre, classroom, horseshoe)',
                    'Primary display — projection or large format display?',
                    'Projector throw distance and screen size if projection',
                    'Secondary displays for overflow / rear of room?',
                    'Podium / lectern position',
                    'Lecturer microphone type — lapel, gooseneck, handheld wireless?',
                    'Audience microphone requirement?',
                    'Recording and lecture capture requirement',
                    'Streaming/webcast requirement',
                    'Existing PC or BYOD input at podium',
                    'Lighting control integration',
                    'Acoustics — reverberation, background noise',
                    'Hearing loop / assistive listening requirement',
                    'Control system complexity — simple input switcher or full AMX/Crestron/Q-SYS',
                ]),
                'install_method' => implode("\n", [
                    '1. First fix — cable containment across ceiling; pull cables to projector/display, podium, speakers, mics and rack',
                    '2. Install projection screen or display mounting structure',
                    '3. Install projector mount and projector; align and focus',
                    '4. Install audience/confidence displays if required',
                    '5. Install ceiling speakers or line array per coverage design',
                    '6. Install and connect amplifier, DSP, switcher and control processor in rack',
                    '7. Install podium with built-in PC, input plate and control touch panel',
                    '8. Install microphone system — wireless receivers racked; mics positioned',
                    '9. Install hearing loop amplifier and perimeter cable if specified',
                    '10. Configure DSP — routing, EQ, auto-mixer, hearing loop level',
                    '11. Configure control system — input selection, volume, projector on/off, lighting presets',
                    '12. Acoustic test and level optimisation',
                    '13. Configure recording/streaming system; test capture quality',
                    '14. Full system demonstration and user training',
                ]),
                'sort_order' => 12,
            ],

        ];

        foreach ($types as $type) {
            SolutionType::updateOrCreate(
                ['slug' => Str::slug($type['name'])],
                array_merge($type, ['slug' => Str::slug($type['name']), 'is_active' => true])
            );
        }
    }
}
