<?php

namespace Database\Seeders;

use App\Models\SolutionType;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class SolutionTypeSeeder extends Seeder
{
    public function run(): void
    {
        $types = [

            // ── 1. Video Conferencing ─────────────────────────────────────────
            [
                'name'        => 'Video Conferencing',
                'description' => 'Teams / Zoom / Cisco room — camera, codec, display, microphone and speaker system for hybrid meetings.',
                'survey_checklist' => implode("\n", [
                    'Room dimensions (W × D × H) — determine display size and camera FOV',
                    'Seating capacity and table configuration (boardroom, U-shape, theatre)',
                    'UC platform in use — Microsoft Teams, Zoom, Cisco Webex, Google Meet',
                    'Existing AV/VC equipment to retain or remove',
                    'Main display position — wall, floor stand, ceiling drop?',
                    'Camera mount position — on display, wall, ceiling?',
                    'Sightline check — can all seats see the display clearly?',
                    'Microphone coverage — ceiling, table or bar mic? Any dead zones?',
                    'Speaker positions — bar below display, ceiling, or existing PA?',
                    'Power outlets near display, table and rack position',
                    'Network ports — quantity and location; PoE availability',
                    'Cable containment route from display to AV rack',
                    'Wall material at display position (plasterboard, brick, glass)',
                    'Ceiling type (suspended, concrete) for cable routing',
                    'Lighting conditions — glare on display from windows?',
                    'Existing HDMI/USB/cable infrastructure to reuse',
                    'AV rack/credenza location and ventilation',
                    'Control system requirement (touch panel, tablet, wall plate)',
                ]),
                'install_method' => implode("\n", [
                    '1. First fix — install cable containment (trunking/conduit), pull AV, USB, network and power cables to all device positions',
                    '2. Mount display bracket to wall; verify wall construction and use appropriate fixings',
                    '3. Install display; dress and terminate all cables at display',
                    '4. Mount camera above or below display; connect USB/HDMI/IP as required',
                    '5. Install microphone (ceiling tiles cut, table grommets, or bar unit positioned)',
                    '6. Build and rack-mount AV equipment — codec, switcher, amplifier, power conditioning',
                    '7. Install control system touch panel or wall plate',
                    '8. Network: connect codec and control system to client IT infrastructure; configure VLANs if required',
                    '9. Power-on and configure codec — enrol device to UC platform tenant',
                    '10. Test: camera framing, microphone coverage, speaker levels, content sharing (HDMI/wireless)',
                    '11. Full end-to-end call test with remote participant',
                    '12. Label all cables; update as-built drawing; user handover',
                ]),
                'sort_order' => 1,
            ],

            // ── 2. Hybrid Meeting Room ────────────────────────────────────────
            [
                'name'        => 'Hybrid Meeting Room',
                'description' => 'Smaller huddle/meeting space optimised for hybrid working — all-in-one bar unit or compact codec with wireless presentation.',
                'survey_checklist' => implode("\n", [
                    'Room capacity (typically 4–8 persons)',
                    'UC platform — Teams, Zoom, or agnostic',
                    'Display size — wall-mounted or existing screen?',
                    'All-in-one bar unit (ClickShare, Neat Bar, Logitech Rally Bar) vs separate components',
                    'Power outlet at display wall for bar unit',
                    'Network/PoE port at display position',
                    'BYOD or dedicated room system?',
                    'Wireless presentation required (ClickShare, AirPlay, Miracast)?',
                    'Existing furniture — table style, seating plan',
                    'Cable route from display to any table connectivity box',
                    'Lighting and glare assessment',
                ]),
                'install_method' => implode("\n", [
                    '1. First fix — pull power and data cables to display and table positions',
                    '2. Mount display bracket; fit and terminate display',
                    '3. Mount all-in-one bar unit below/above display; connect power and network',
                    '4. Install table connectivity box (HDMI, USB-C, power) if required',
                    '5. Enrol device to UC platform; configure meeting room account',
                    '6. Configure wireless presentation unit if included',
                    '7. Test call, sharing and audio — adjust camera framing and mic sensitivity',
                    '8. User handover and labelling',
                ]),
                'sort_order' => 2,
            ],

            // ── 3. Digital Signage ────────────────────────────────────────────
            [
                'name'        => 'Digital Signage',
                'description' => 'Single or multi-display signage — commercial displays, media players and CMS-driven content.',
                'survey_checklist' => implode("\n", [
                    'Display location — wall, portrait or landscape, freestanding?',
                    'Wall construction at mount position (stud, masonry, glass, partition)',
                    'Display size and viewing distance — minimum 6× display height for comfortable reading',
                    'Ambient light levels — direct sunlight? High-brightness display needed?',
                    'Power outlet proximity or new spur required',
                    'Network/data connection — wired Ethernet or WiFi?',
                    'Content source — local media player, CMS network player, built-in SoC?',
                    'CMS platform in use or to be recommended',
                    'Cable route — through wall, trunking or surface mounted',
                    'Fire/planning considerations for large format or double-sided units',
                    'Bracket type — fixed, tilt or VESA specification',
                    'Interactivity required (touch overlay)?',
                ]),
                'install_method' => implode("\n", [
                    '1. First fix — install cable containment; pull power and data cables to display position',
                    '2. Mark and fix wall bracket using appropriate fixings for wall construction',
                    '3. Hang display and secure; cable dress and connection at rear',
                    '4. Install and connect media player / SoC configuration',
                    '5. Connect to network; configure IP settings',
                    '6. Enrol display in CMS; assign content schedule',
                    '7. Test display orientation, content playback and auto on/off schedule',
                    '8. Label and photograph installation; update asset register',
                ]),
                'sort_order' => 3,
            ],

            // ── 4. PA / Sound System ──────────────────────────────────────────
            [
                'name'        => 'PA / Sound System',
                'description' => 'Background music, paging and public address — ceiling or surface-mount speakers, amplifiers, DSP and source inputs.',
                'survey_checklist' => implode("\n", [
                    'Room dimensions and volume — determine speaker quantity and spacing',
                    'Ceiling type — suspended grid (easy), plasterboard, concrete, open truss',
                    'Ceiling height — affects speaker SPL and coverage angle selection',
                    'Background noise level estimate (open plan office, plant room, reception)',
                    'Number of audio zones required',
                    'Source inputs required — microphone, line-level, streaming, telephone paging',
                    'Emergency voice alarm (EVA) or fire alarm integration required?',
                    'Existing speaker positions and wiring to reuse',
                    'Amplifier and DSP rack location',
                    'Cable route from amp rack to all speaker positions',
                    'Volume control positions in each zone',
                    'AV rack power supply and ventilation',
                    'Client music source (Spotify, DAB, local playlist)',
                ]),
                'install_method' => implode("\n", [
                    '1. Mark out speaker positions per coverage design (typically 1× ceiling height spacing)',
                    '2. First fix — pull 2-core 1.5mm speaker cable from amp position to each speaker drop',
                    '3. Install cable containment above ceiling/in roof void',
                    '4. Cut ceiling tiles or drill penetrations for speaker backboxes',
                    '5. Fit speaker backboxes or brackets',
                    '6. Install and terminate amplifier, DSP and source equipment in rack',
                    '7. Connect and label all speaker runs at amplifier/DSP outputs',
                    '8. Install zone volume controls and input plates at designated positions',
                    '9. Power-on and configure DSP — EQ, routing, input gain, zone levels',
                    '10. Acoustic test — measure SPL in each zone; adjust EQ and levels',
                    '11. Test paging mic, all sources and zone independence',
                    '12. User handover; provide DSP backup file',
                ]),
                'sort_order' => 4,
            ],

            // ── 5. LED Video Wall ─────────────────────────────────────────────
            [
                'name'        => 'LED Video Wall',
                'description' => 'Direct-view LED panels — fine pitch indoor or outdoor LED wall with video processor.',
                'survey_checklist' => implode("\n", [
                    'Available wall area (W × H) and target display size',
                    'Wall construction — must support significant weight (LED cabinets 10–25 kg/m²)',
                    'Floor-standing or wall-mounted structure?',
                    'Floor loading assessment if large or multi-tier installation',
                    'Pixel pitch selection — viewing distance (minimum 1× PP in metres = min viewing distance in mm)',
                    'Ambient light levels — brightness (nits) specification',
                    'Power requirements — total draw, phase availability, UPS requirement',
                    'Cable routes for power and data from processor to wall',
                    'Video processor location and signal source inputs',
                    'Rear service access or front-service cabinets required?',
                    'Control room / operator position',
                    'Cooling and ventilation in the space',
                    'Network connection for remote monitoring/control',
                    'Structural engineer sign-off required?',
                ]),
                'install_method' => implode("\n", [
                    '1. Structural assessment and approval for wall or floor-standing frame',
                    '2. Fabricate and install steel subframe structure; level and plumb',
                    '3. First fix — install power distribution boards and data cabling to frame',
                    '4. Mount LED cabinets row by row from bottom; level each row',
                    '5. Connect inter-cabinet data and power looms',
                    '6. Install and rack video processor; connect signal sources',
                    '7. Run main data link from processor to first cabinet',
                    '8. Power-on; configure video processor resolution and mapping',
                    '9. Cabinet calibration — uniformity, brightness and colour correction using manufacturer software',
                    '10. Test all content inputs and signal distribution',
                    '11. Install any facade trims or bezels',
                    '12. Hand over processor files and calibration data; train operator',
                ]),
                'sort_order' => 5,
            ],

            // ── 6. LCD Video Wall ─────────────────────────────────────────────
            [
                'name'        => 'LCD Video Wall',
                'description' => 'Ultra-narrow bezel LCD panel array — typically 2×2 to 6×4 configurations with video wall controller.',
                'survey_checklist' => implode("\n", [
                    'Number of displays — rows × columns configuration',
                    'Display size (46", 49", 55") and bezel specification',
                    'Wall construction and fixing capability for combined weight',
                    'Floor space for service access (minimum 600mm front clearance)',
                    'Power outlets — one per display or shared spur',
                    'Video wall controller location and PC/media source inputs',
                    'Signal distribution method — fibre, Cat6 extenders, direct cabling',
                    'Control system for on/off scheduling',
                    'Existing cable containment or new trunking required',
                    'Landscape or portrait orientation of individual panels',
                    'Ambient light and glare assessment',
                ]),
                'install_method' => implode("\n", [
                    '1. Mark wall grid and fix primary mounting rail system; check level across full width',
                    '2. First fix — pull power and signal cables to each panel position',
                    '3. Install displays onto mounting system row by row; pixel-align bezels',
                    '4. Connect power and signal (DP/HDMI) cables to each display',
                    '5. Install video wall controller in rack; connect all signal outputs',
                    '6. Power-on; configure video wall controller — display layout, resolution, bezel compensation',
                    '7. Align and calibrate colour/brightness uniformity across panels',
                    '8. Test all input sources and switching',
                    '9. Configure scheduling/control system',
                    '10. Document configuration; train operator',
                ]),
                'sort_order' => 6,
            ],

            // ── 7. Interactive / Collaboration ────────────────────────────────
            [
                'name'        => 'Interactive / Collaboration',
                'description' => 'Interactive flat panel display (IFP) for collaborative working, teaching or design review.',
                'survey_checklist' => implode("\n", [
                    'Room type — classroom, training, design studio, boardroom',
                    'Display size (65", 75", 86", 98") — viewing distance and seating plan',
                    'Wall position — clear of windows, central sightline',
                    'Wall construction for bracket fixing',
                    'Mounting height — standing use (centre ~140cm AFF) or seated?',
                    'Existing whiteboard or projector screen to remove?',
                    'PC source — built-in OPS module, external PC, or BYOD?',
                    'USB-C / HDMI table connectivity required?',
                    'Wireless presentation required?',
                    'Power outlet at display wall position',
                    'Network port at display (for updates, remote management)',
                    'Cable route for any external PC or table box',
                    'Acoustic treatment if voice recognition / AI features used',
                ]),
                'install_method' => implode("\n", [
                    '1. Remove existing display, projector or whiteboard if required; make good wall',
                    '2. First fix — pull power, network and AV cables to display position',
                    '3. Install floor-standing bracket or wall bracket using correct fixings',
                    '4. Fit display; dress and terminate all cables',
                    '5. Install OPS/PC module if specified',
                    '6. Install wireless presentation unit if required',
                    '7. Install table connectivity box and cable management if specified',
                    '8. Power-on; configure display — input settings, touch calibration, OS setup',
                    '9. Install required apps and software; connect to WiFi/Ethernet',
                    '10. Test touch, stylus, wireless sharing and all inputs',
                    '11. User handover and training on interactive features',
                ]),
                'sort_order' => 7,
            ],

            // ── 8. Divisible / Twin Room ──────────────────────────────────────
            [
                'name'        => 'Divisible / Twin Room',
                'description' => 'Two rooms separated by a moveable partition wall that can operate independently or as one combined space.',
                'survey_checklist' => implode("\n", [
                    'Partition wall type — acoustic, operable, fixed?',
                    'Combined room dimensions vs individual room dimensions',
                    'AV requirement in each half independently',
                    'Combined mode AV requirement — linked displays, combined audio?',
                    'Display positions in each zone — avoid partition wall overlap',
                    'Audio zone independence — separate amps or DSP matrix routing',
                    'Microphone strategy — individual room or combined array?',
                    'Control system — single touch panel with mode switching or separate panels?',
                    'Partition sensor integration for automatic mode switching?',
                    'Cable containment — above partition or through dedicated conduit',
                    'Power supply to each zone independently',
                    'Network infrastructure for each room AV system',
                ]),
                'install_method' => implode("\n", [
                    '1. Survey both room halves and confirm partition line and operation',
                    '2. First fix — pull cables for each zone plus combined-mode spurs above ceiling void',
                    '3. Install displays, cameras, microphones and speakers in each zone as per individual room type',
                    '4. Install DSP / matrix switcher with independent zone outputs and combined bus',
                    '5. Install partition open/close sensor wiring if required',
                    '6. Commission each room independently — test AV in isolation',
                    '7. Configure DSP routing for combined mode — merge audio zones, extend video',
                    '8. Configure control system modes (Room A only / Room B only / Combined)',
                    '9. Test all three operating modes end-to-end',
                    '10. User handover — demonstrate mode switching procedure',
                ]),
                'sort_order' => 8,
            ],

            // ── 9. Audio Conferencing Only ────────────────────────────────────
            [
                'name'        => 'Audio Conferencing Only',
                'description' => 'Speakerphone or ceiling mic / speaker system for audio-only conference calls — no video.',
                'survey_checklist' => implode("\n", [
                    'Room size and seating capacity',
                    'UC/telephony platform — Teams Audio, Zoom Phone, traditional PSTN',
                    'Existing PSTN/IP phone infrastructure',
                    'Table configuration — determine speakerphone positioning',
                    'Ceiling mic preferred or table unit acceptable?',
                    'Existing network port at table or ceiling',
                    'Power at table position for speakerphone',
                    'Acoustic treatment — echo, reverberation issues?',
                    'Privacy/confidentiality requirement (sound masking?)',
                ]),
                'install_method' => implode("\n", [
                    '1. Install network outlet at table or ceiling mic position if not present',
                    '2. Pull power cable to table for speakerphone or PoE for ceiling unit',
                    '3. Install ceiling mic / speaker unit in tile or surface mount',
                    '4. Connect to network switch; configure PoE if required',
                    '5. Enrol device to UC platform; configure audio settings',
                    '6. Acoustic test — place call and verify coverage, echo cancellation, clarity',
                    '7. Label and document device IP/MAC for IT records',
                ]),
                'sort_order' => 9,
            ],

            // ── 10. Upgrade / Strip-out ───────────────────────────────────────
            [
                'name'        => 'Upgrade / Strip-out',
                'description' => 'Removal and replacement of legacy AV equipment — full or partial strip-out before new installation.',
                'survey_checklist' => implode("\n", [
                    'Full inventory of existing AV equipment (make, model, condition)',
                    'Items confirmed for removal — obtain written client approval',
                    'Items confirmed to retain and reuse',
                    'Existing cable infrastructure — reuse or replace?',
                    'Cable containment condition — trunking, conduit, ceiling voids',
                    'Wall/ceiling make-good required after removal?',
                    'Disposal method — client to arrange skip, or 21CAV to remove?',
                    'WEEE / data destruction requirements for removed equipment',
                    'Working hours restrictions — after hours strip-out required?',
                    'Access to ceiling voids and risers',
                    'Asbestos survey required (pre-1990 buildings)?',
                    'Photographs of existing installation for records',
                ]),
                'install_method' => implode("\n", [
                    '1. Photograph all existing equipment positions and cable routes before disconnection',
                    '2. Power-down and isolate all circuits — confirm with site electrician',
                    '3. Disconnect and remove displays, processors, racks — label or bag cables for client reference',
                    '4. Remove cable containment and pull all redundant cables',
                    '5. Make good wall/ceiling penetrations — fill, sand and paint to match where required',
                    '6. Remove and dispose of equipment in accordance with WEEE regulations',
                    '7. Site clean — remove all waste and packaging',
                    '8. Photo record of stripped space; sign-off with client before new install commences',
                    '9. Proceed with new installation as per separate solution type specification',
                ]),
                'sort_order' => 10,
            ],

            // ── 11. AV Infrastructure / Rack Build ────────────────────────────
            [
                'name'        => 'AV Infrastructure / Rack Build',
                'description' => 'Head-end rack build, cable infrastructure, patch panels and signal distribution for a multi-room system.',
                'survey_checklist' => implode("\n", [
                    'Rack room / IDF cupboard location and dimensions',
                    'Rack size required (6U, 12U, 22U, 42U)',
                    'Floor or wall-mount rack?',
                    'Ventilation and cooling in rack room',
                    'Dedicated AV power circuits — quantity, amperage',
                    'UPS requirement and runtime specification',
                    'Cable route from rack room to each room — floor, ceiling, risers',
                    'Conduit or trunking sizing for cable volume',
                    'Fibre or Cat6 for long-distance signal distribution',
                    'Existing IT patch panels / switch to integrate with',
                    'Remote monitoring / management requirement',
                    'Access control to rack room',
                ]),
                'install_method' => implode("\n", [
                    '1. Install rack enclosure; level and secure to floor or wall',
                    '2. Install power distribution unit (PDU), UPS and cable management',
                    '3. Pull all main trunk cables from rack room to each room end-point',
                    '4. Install patch panels and label all ports (patch schedule)',
                    '5. Rack-mount all head-end equipment — switcher, amplifier, processor, control system',
                    '6. Terminate and patch all cable runs; test continuity',
                    '7. Install network switch if AV-dedicated; configure VLANs',
                    '8. Power-on; configure all rack equipment',
                    '9. Test signal distribution to all rooms end-to-end',
                    '10. Install blanking panels; dress and cable-tie all internal rack cabling',
                    '11. Label all equipment; produce as-built rack elevation drawing',
                    '12. Remote monitoring / control system final configuration',
                ]),
                'sort_order' => 11,
            ],

            // ── 12. Lecture / Training Room ───────────────────────────────────
            [
                'name'        => 'Lecture / Training Room',
                'description' => 'Presentation-focused room — lecturer display, audience displays, podium PC, microphone and recording capability.',
                'survey_checklist' => implode("\n", [
                    'Room capacity and seating layout (theatre, classroom, horseshoe)',
                    'Primary display — projection or large format display?',
                    'Projector throw distance and screen size if projection',
                    'Secondary displays for overflow / rear of room?',
                    'Podium / lectern position',
                    'Lecturer microphone type — lapel, gooseneck, handheld wireless?',
                    'Audience microphone requirement?',
                    'Recording and lecture capture requirement',
                    'Streaming/webcast requirement',
                    'Existing PC or BYOD input at podium',
                    'Lighting control integration',
                    'Acoustics — reverberation, background noise',
                    'Hearing loop / assistive listening requirement',
                    'Control system complexity — simple input switcher or full AMX/Crestron/Q-SYS',
                ]),
                'install_method' => implode("\n", [
                    '1. First fix — cable containment across ceiling; pull cables to projector/display, podium, speakers, mics and rack',
                    '2. Install projection screen or display mounting structure',
                    '3. Install projector mount and projector; align and focus',
                    '4. Install audience/confidence displays if required',
                    '5. Install ceiling speakers or line array per coverage design',
                    '6. Install and connect amplifier, DSP, switcher and control processor in rack',
                    '7. Install podium with built-in PC, input plate and control touch panel',
                    '8. Install microphone system — wireless receivers racked; mics positioned',
                    '9. Install hearing loop amplifier and perimeter cable if specified',
                    '10. Configure DSP — routing, EQ, auto-mixer, hearing loop level',
                    '11. Configure control system — input selection, volume, projector on/off, lighting presets',
                    '12. Acoustic test and level optimisation',
                    '13. Configure recording/streaming system; test capture quality',
                    '14. Full system demonstration and user training',
                ]),
                'sort_order' => 12,
            ],

            // ── 13. Conferencing (Teams / Zoom Room) ──────────────────────────
            [
                'name'        => 'Conferencing (Teams / Zoom Room)',
                'description' => 'Certified Microsoft Teams Room or Zoom Room deployment with dedicated compute, camera, mic array and touch controller.',
                'survey_checklist' => implode("\n", [
                    'Room dimensions (W × D × H)',
                    'Seating capacity and table layout',
                    'Display size and viewing distance to furthest seat',
                    'Ceiling height and speaker/mic mounting options',
                    'Network infrastructure (dedicated VLAN, PoE switch, available bandwidth)',
                    'Teams/Zoom tenant details and IT contact for provisioning',
                    'Power outlets at display wall, table, and equipment location',
                    'Cable containment routes (display wall, table, ceiling void)',
                    'Ambient noise level and acoustic treatment present',
                    'Touch controller mounting location (wall or table)',
                    'Existing VC equipment to retain, replace, or remove',
                    'Camera field of view — confirm no obstructions',
                    'Room booking system integration requirement',
                    'Ventilation/cooling at AV equipment location',
                ]),
                'install_method' => implode("\n", [
                    '1. First fix — install cable containment, pull AV, USB, data and power cables',
                    '2. Mount display bracket to wall; verify level and structural fixing',
                    '3. Install and connect certified VC camera (PTZ or fixed-angle)',
                    '4. Install and connect room audio system (integrated bar, ceiling mics, or table mic array)',
                    '5. Hang and connect display; dress cables behind bracket',
                    '6. Install compute unit (MTR/Zoom Room engine) in rack or hidden mount',
                    '7. Install and cable touch controller panel at wall or table',
                    '8. Connect all peripherals to compute unit',
                    '9. Power on; complete initial device setup and Windows/Android configuration',
                    '10. Enrol device in Teams/Zoom tenant; configure room account and calendar integration',
                    '11. Test inbound and outbound calls; verify camera, mic, and speaker operation',
                    '12. Configure display name, room settings, and default layout',
                    '13. Conduct sign-off call with IT and end user',
                    '14. Label all cables; complete as-built cable schedule',
                ]),
                'sort_order' => 13,
            ],

            // ── 14. BYOD Conferencing ─────────────────────────────────────────
            [
                'name'        => 'BYOD Conferencing',
                'description' => 'Bring-your-own-device huddle or meeting space — USB/HDMI connectivity point, room camera, speakerphone and display with no fixed codec.',
                'survey_checklist' => implode("\n", [
                    'Room dimensions and maximum occupancy',
                    'Table or desk layout and cable management options',
                    'HDMI/USB-C/USB-A connection point location (table cubby, floor box, or wall plate)',
                    'Power outlet at table position for BYOD device charging',
                    'Network availability (wired and wireless for guest devices)',
                    'Existing display or new display required',
                    'Cable routing method (surface trunking, floor box, or concealed)',
                    'Wireless presentation system requirement (e.g. ClickShare, Solstice)',
                    'Room audio requirement (USB speakerphone, ceiling speaker bar, or none)',
                    'USB webcam requirement if no integrated camera',
                    'Lighting conditions at table for camera use',
                ]),
                'install_method' => implode("\n", [
                    '1. Install cable containment; pull HDMI, USB and power cables to connection point',
                    '2. Mount display bracket; install and connect display',
                    '3. Install table cable cubby, floor box, or wall plate at table position',
                    '4. Fit HDMI, USB-A and USB-C connection plate or cable fly leads',
                    '5. Install room speakerphone or USB speaker bar and connect to connection point',
                    '6. Install USB webcam at display if required',
                    '7. Install wireless presentation system (if in scope)',
                    '8. Test all connections with a BYOD laptop — verify display, audio, and video',
                    '9. Label connections; complete install record',
                ]),
                'sort_order' => 14,
            ],

            // ── 15. Split / Divisible Room ────────────────────────────────────
            [
                'name'        => 'Split / Divisible Room',
                'description' => 'Partition-divided space with AV operable independently in each half or combined as a single room — requires switching, separate control, and partition interface cabling.',
                'survey_checklist' => implode("\n", [
                    'Room dimensions in full and split configurations',
                    'Partition/wall type, manufacturer, and acoustic rating (STC value)',
                    'Partition opening mechanism and interface panel locations',
                    'Existing AV in each half (to retain, reuse, or replace)',
                    'Signal switching/distribution method (separate systems or shared switcher)',
                    'Cable routing path through or above partition',
                    'Power and data availability in each half independently',
                    'Control system requirement (separate touchpanels, combined, or linked)',
                    'Microphone coverage required in each configuration',
                    'Display or projection in each half (size, position, mounting)',
                    'IT network segregation requirement when room is split',
                    'Audio bleed between halves — confirm acoustic performance',
                ]),
                'install_method' => implode("\n", [
                    '1. Agree partition interface points and cable pass-through with main contractor',
                    '2. First fix — install containment and pull cables in each half independently',
                    '3. Install displays or projection system in both halves',
                    '4. Install ceiling or surface speakers and microphones in both halves',
                    '5. Install AV switching and distribution equipment for split and combined modes',
                    '6. Install control system touchpanels in each half',
                    '7. Install partition interface cabling (signal and control pass-through)',
                    '8. Program control system for split (A only), split (B only), and combined modes',
                    '9. Commission audio levels and acoustic echo cancellation in each configuration',
                    '10. Test all operating modes including mid-session partition close/open transitions',
                    '11. Handover and user training on partition AV operation',
                ]),
                'sort_order' => 15,
            ],

            // ── 16. Projection / Screen System ───────────────────────────────
            [
                'name'        => 'Projection / Screen System',
                'description' => 'Projector with fixed, motorised or tab-tensioned screen — suitable for training rooms, classrooms, conference rooms and auditoria.',
                'survey_checklist' => implode("\n", [
                    'Room dimensions (W × D × H)',
                    'Throw distance from proposed projector position to screen wall',
                    'Ceiling height and mounting option (ceiling plate, drop rod, beam shelf)',
                    'Structural suitability at projector mount point (solid concrete, timber joist, steel beam)',
                    'Ambient light levels — windows, rooflights, existing blinds or blackout',
                    'Screen type required (fixed frame, motorised cassette, tab-tensioned, short-throw wall)',
                    'Screen size and aspect ratio (16:9, 4:3, 2.35:1)',
                    'Power outlet at projector mounting position',
                    'Signal source locations (lectern, wall plate, table)',
                    'Cable routing from sources to projector position (ceiling void or surface)',
                    'Lens type required (standard, short-throw, ultra short-throw, long-throw)',
                    'Keystone or lens shift constraints from mounting position',
                    'Network connection for projector IP management or lamp monitoring',
                    'Existing projector or screen to remove',
                ]),
                'install_method' => implode("\n", [
                    '1. Mark out projector mounting position; confirm throw calculation with lens spec sheet',
                    '2. Install structural anchor points — drop rods, unistrut or ceiling bracket',
                    '3. Install cable containment; pull power, HDMI/HDBaseT and control cables',
                    '4. Install motorised screen bracket and cassette, or fixed/tensioned frame',
                    '5. Mount projector to ceiling mount; adjust position on drop rods',
                    '6. Connect signal and control cables to projector',
                    '7. Power on projector; perform lens zoom, shift and focus',
                    '8. Align projected image to screen; correct geometry and keystone',
                    '9. Install and connect AV source switching or wall plates',
                    '10. Integrate motorised screen relay or RS-232/IP control if in scope',
                    '11. Install blackout blinds or integrate with existing motorisation (if in scope)',
                    '12. Test all source inputs; verify contrast and brightness',
                    '13. Log projector serial number, lamp hours and register warranty',
                ]),
                'sort_order' => 16,
            ],

            // ── 17. Simple Display / TV Install ──────────────────────────────
            [
                'name'        => 'Simple Display / TV Install',
                'description' => 'Single commercial or consumer flat panel installation — wall-mounted with basic source connectivity. No VC system, no CMS.',
                'survey_checklist' => implode("\n", [
                    'Display size and proposed mounting location',
                    'Wall construction (masonry, stud/plasterboard, timber frame, glass partition)',
                    'Structural suitability for bracket weight at proposed position',
                    'Power outlet location and proximity — new socket required?',
                    'Signal source type (HDMI wall plate, media player, set-top box, direct PC)',
                    'Cable routing method (surface trunking, concealed in chase, or skirting)',
                    'Mounting height, tilt and swivel requirements',
                    'Network connection for smart display management or HDMI-CEC',
                    'Existing display to remove and dispose',
                    'Access for installation (step ladders sufficient or MEWP/podium required)',
                ]),
                'install_method' => implode("\n", [
                    '1. Mark out bracket fixing positions; identify wall construction and select fixings',
                    '2. Install wall bracket — level, anchored to masonry plugs, studs, or specialist fixings',
                    '3. Install cable trunking or cut/chase concealed cable route',
                    '4. Pull power extension or spur and HDMI signal cable to bracket',
                    '5. Hang display on bracket; dress and secure cables behind screen',
                    '6. Connect power and signal inputs; power on',
                    '7. Set input source, picture mode and display name',
                    '8. Adjust tilt and height; confirm viewing angle from seating position',
                    '9. Remove packaging; dispose of old display if in scope',
                ]),
                'sort_order' => 17,
            ],

            // ── 18. Boardroom / Executive Suite ──────────────────────────────
            [
                'name'        => 'Boardroom / Executive Suite',
                'description' => 'High-specification integrated AV with touch-panel control system (Crestron, AMX, QSC or Extron), full VC, presentation switching, lighting and blind integration.',
                'survey_checklist' => implode("\n", [
                    'Room dimensions and seating capacity',
                    'Display type and position (wall-hung, ceiling recess, floor-rise, dual screens)',
                    'Table dimensions, material and cable management requirements (wire tray, floor box)',
                    'Touch control panel locations (wall, table-top, credenza)',
                    'VC system type (codec, all-in-one bar, MTR/Zoom Room)',
                    'Camera field of view and position — no obstructions',
                    'Microphone system type (table boundary, ceiling beam-tracking, or gooseneck)',
                    'Ceiling speaker positions and driver size',
                    'Lighting control integration (manufacturer, protocol — DALI, DMX, Lutron)',
                    'Motorised blind/shade integration requirement',
                    'Equipment rack/cabinet location, dimensions and ventilation',
                    'Network infrastructure (dedicated VLAN, available bandwidth, PoE)',
                    'Power positions (table, credenza, rack, display wall)',
                    'Cable containment routes (under floor, ceiling void, wall chases)',
                    'Finish and aesthetics requirements (flush faceplates, cable reveals, RAL colour)',
                    'IT/BMS integration points and contacts',
                    'Existing AV equipment to retain, integrate, or remove',
                ]),
                'install_method' => implode("\n", [
                    '1. Co-ordinate first fix programme with main contractor (containment, back boxes, conduit)',
                    '2. Install cable containment throughout; pull all AV, control, data and power cables',
                    '3. Install display brackets, screen housing, ceiling apertures or floor-rise mechanism',
                    '4. Install and connect all displays and screens',
                    '5. Build rack/equipment cabinet — install rails, power distribution, patch panels',
                    '6. Install and connect VC system (camera, codec/compute, speaker bar or ceiling array)',
                    '7. Install in-ceiling speakers and connect to amplifier',
                    '8. Install microphone system (table mics, gooseneck or beam-tracking ceiling array)',
                    '9. Install control system processor; complete system wiring to control ports',
                    '10. Install touchpanels at wall and/or table positions',
                    '11. Load control system program; commission all device drivers',
                    '12. Integrate with lighting, motorised blinds and room booking system',
                    '13. Commission audio DSP — levels, EQ, gain structure, echo cancellation',
                    '14. Test all VC calls and presentation source switching',
                    '15. Conduct 48-hour AV soak test',
                    '16. Handover walkthrough and user training session; complete O&M pack',
                ]),
                'sort_order' => 18,
            ],

            // ── 19. IPTV / Satellite Distribution ────────────────────────────
            [
                'name'        => 'IPTV / Satellite Distribution',
                'description' => 'Multi-room TV and video distribution — headend encoding/modulation with IPTV decoders, satellite or Freeview reception to multiple display locations.',
                'survey_checklist' => implode("\n", [
                    'Number of display locations and floor plan layout',
                    'Signal sources required (Sky, Virgin, Freeview, IPTV headend, streaming services)',
                    'Existing cabling infrastructure (coax, Cat6, fibre)',
                    'Network infrastructure (bandwidth, IGMP snooping enabled, multicast routing)',
                    'Headend/equipment room location and available rack space',
                    'Power availability at headend location',
                    'Display mounting positions (existing or new)',
                    'Number of channels required simultaneously',
                    'Interactive or non-interactive (non-zapping) requirement',
                    'Audio zone distribution requirement alongside video',
                    'Remote management/monitoring requirement',
                ]),
                'install_method' => implode("\n", [
                    '1. Install headend rack enclosure and power distribution',
                    '2. Install satellite dish or aerial at roof/external location; run coax to headend',
                    '3. Install and configure encoding/modulation equipment (encoders, IP streamers)',
                    '4. Install IPTV headend server and configure channel lineup and EPG',
                    '5. Install Cat6 or coax distribution cabling to all display locations',
                    '6. Install IPTV set-top boxes or decoders at each display',
                    '7. Connect decoders to displays; configure input sources',
                    '8. Test all channels at all display locations',
                    '9. Configure remote control pairing at each location',
                    '10. Test interactive features and EPG navigation',
                    '11. Document channel lineup and handover login credentials to client IT',
                ]),
                'sort_order' => 19,
            ],

            // ── 20. Stage / Event Infrastructure ─────────────────────────────
            [
                'name'        => 'Stage / Event Infrastructure',
                'description' => 'Permanent or semi-permanent stage and event space — PA system, stage monitoring, projection or LED, lighting rig, video switching and FOH infrastructure.',
                'survey_checklist' => implode("\n", [
                    'Stage dimensions (W × D) and clear height to ceiling or truss',
                    'Rigging points available (flying) — rated load per point',
                    'Load-bearing capacity of ceiling, beams or dedicated truss',
                    'Power distribution available (three-phase, 32A/63A commando sockets, UPS)',
                    'Throw distance and surface for projection or LED screen',
                    'PA coverage area and audience capacity',
                    'Stage monitoring requirement (wedges, in-ear, or none)',
                    'Acoustic environment (RT60, background noise, reflective surfaces)',
                    'Lighting rig positions and existing dimmer/DMX infrastructure',
                    'Video switching and streaming or recording requirement',
                    'Comms/IEM (in-ear monitor) system requirement',
                    'FOH (front of house) position — sightlines and cable route',
                    'Cable management across stage area (cable ramps, trays, conduit)',
                    'Adjacent areas for FOH mix position and backstage rack',
                ]),
                'install_method' => implode("\n", [
                    '1. Structural survey and rigging inspection; obtain engineer sign-off on flying loads',
                    '2. Install truss or rigging system; safety bond all flown equipment',
                    '3. Install power distribution (distro boxes, stage-pin or commando outlets, data cabling)',
                    '4. Fly or ground-stack PA speaker system; run speaker cable to amplifier rack',
                    '5. Install stage monitor wedges and connect to amplifier/DSP',
                    '6. Install front fills or under-stage speakers if required',
                    '7. Install projection system or LED screen (fly or ground support)',
                    '8. Install lighting rig; patch dimmer circuits and DMX universe',
                    '9. Install video switcher, streaming encoder and recording infrastructure',
                    '10. Commission audio system — set gain structure, DSP routing, system drive',
                    '11. Commission lighting rig; program house, wash and spot scenes',
                    '12. Test all signal paths end-to-end from sources to outputs',
                    '13. Full technical run-through with event team; adjust mix and levels',
                    '14. Complete as-built drawings, patch schedules and handover documentation',
                ]),
                'sort_order' => 20,
            ],

            // ── 21. Acoustic Treatment ────────────────────────────────────────
            [
                'name'        => 'Acoustic Treatment',
                'description' => 'Supply and installation of acoustic absorber panels, diffusers and bass traps to achieve a target RT60 or improve speech intelligibility in meeting, recording or teaching spaces.',
                'survey_checklist' => implode("\n", [
                    'Room dimensions and volume (calculate cubic metres)',
                    'Current RT60 measurement or estimated reverberation time',
                    'Wall, floor and ceiling surface materials and finishes',
                    'Target RT60 or acoustic performance specification (e.g. BB93, BS 8233)',
                    'Proposed positions for absorbers, diffusers and bass traps',
                    'Wall and ceiling fixing suitability at proposed panel positions',
                    'Aesthetic requirements (fabric colour, panel profile, edge detail, RAL colour)',
                    'Existing acoustic treatment to remove',
                    'Furniture and room layout impact on treatment positions',
                    'Access for installation (step ladders or podium)',
                ]),
                'install_method' => implode("\n", [
                    '1. Survey and agree panel positions with acoustic consultant and client',
                    '2. Mark out panel locations; confirm fixing suitability (masonry, plasterboard, timber)',
                    '3. Install timber battens or sub-frame where direct fixing is not suitable',
                    '4. Fix acoustic absorber panels to walls at agreed positions',
                    '5. Install corner bass traps — floor to ceiling or ceiling corner units',
                    '6. Fix diffuser panels at reflection points as specified',
                    '7. Install ceiling-mounted baffles or clouds if in scope',
                    '8. Measure RT60 post-installation using calibrated microphone and software',
                    '9. Review result against target; adjust panel quantity or position if needed',
                    '10. Final sign-off RT60 measurement; issue acoustic report to client',
                ]),
                'sort_order' => 21,
            ],

        ];

        foreach ($types as $type) {
            SolutionType::updateOrCreate(
                ['slug' => Str::slug($type['name'])],
                array_merge($type, ['slug' => Str::slug($type['name']), 'is_active' => true])
            );
        }
    }
}
