@extends('layouts.app')

@section('title', $drawing->kindLabel().' — '.$project->name)

@push('styles')
    @vite(['resources/css/app.css', 'resources/js/app.js'])
    <style>
        [x-cloak] { display: none !important; }
        .badge-grey   { background-color: #E5E7EB; color: #374151; }
        .badge-yellow { background-color: #FEF3C7; color: #92400E; }
        .badge-green  { background-color: #D1FAE5; color: #065F46; }
        .badge-teal   { background-color: #CCFBF1; color: #115E59; }
        .badge-blue   { background-color: #DBEAFE; color: #1E40AF; }
        .badge-red    { background-color: #FEE2E2; color: #991B1B; }
        /* Embedded SVG container — let the SVG scale to its viewBox. */
        .drawing-svg-container svg { max-width: 100%; height: auto; display: block; margin: 0 auto; }
    </style>
@endpush

@section('content')
<div class="max-w-7xl mx-auto p-6">
    <div class="flex items-center justify-between mb-4 flex-wrap gap-3">
        <div class="min-w-0">
            <a href="{{ route('projects.drawings.index', $project) }}" class="text-sm text-accent-700 hover:underline">← All drawings</a>
            <h1 class="text-2xl font-semibold mt-1 truncate">
                {{ $drawing->kindLabel() }} — {{ $drawing->room?->name ?? 'Whole project' }}
            </h1>
            <p class="text-sm text-gray-500">
                Revision {{ $drawing->revisionLabel() }} · {{ $drawing->kind }}
                @if ($drawing->generatedBy)
                    · Generated by {{ $drawing->generatedBy->name ?? 'Unknown' }}
                @endif
            </p>
        </div>
        <div class="flex items-center gap-3 flex-wrap justify-end">
            @include('projects.drawings._status-pill', ['drawing' => $drawing])
            @if ($drawing->isRack())
                {{-- Phase 18 Plan 03 — rack editor entry. Sits next to the
                     existing Download / Regenerate buttons. The rendered SVG
                     itself flows through the existing kind-agnostic render
                     branch at line ~55 (Warning 9 fix — no second render
                     branch added). --}}
                <a href="{{ route('projects.drawings.edit', [$project, $drawing]) }}"
                   class="inline-flex items-center bg-accent-600 hover:bg-accent-700 text-white font-medium px-3 py-1.5 rounded-md text-sm">
                    Edit Rack
                </a>
            @endif
            @if ($drawing->isReady())
                <a href="{{ route('projects.drawings.download', [$project, $drawing, 'pdf']) }}"
                   class="inline-flex items-center border border-gray-300 hover:bg-gray-50 text-gray-700 px-3 py-1.5 rounded-md text-sm">Download PDF</a>
                <a href="{{ route('projects.drawings.download', [$project, $drawing, 'svg']) }}"
                   class="inline-flex items-center border border-gray-300 hover:bg-gray-50 text-gray-700 px-3 py-1.5 rounded-md text-sm">Download SVG</a>
                <a href="{{ route('projects.drawings.download', [$project, $drawing, 'png']) }}"
                   class="inline-flex items-center border border-gray-300 hover:bg-gray-50 text-gray-700 px-3 py-1.5 rounded-md text-sm">Download PNG</a>
            @endif
            <button type="button"
                    x-data
                    @click="$dispatch('open-regenerate-confirm', { id: {{ $drawing->id }}, hasUserEdits: {{ $drawing->hasUserEdits() ? 'true' : 'false' }} })"
                    class="inline-flex items-center border border-gray-300 hover:bg-gray-50 text-gray-700 px-3 py-1.5 rounded-md text-sm">
                Regenerate
            </button>
        </div>
    </div>

    {{-- ───── Drawing preview ─────────────────────────────────────── --}}
    @if ($drawing->isReady() && ! empty($drawing->generated_svg))
        <div class="bg-white border border-gray-200 rounded-lg p-6 overflow-auto drawing-svg-container">
            {!! $drawing->generated_svg !!}
        </div>
    @elseif ($drawing->status === \App\Models\ProjectDrawing::STATUS_GENERATING)
        <div class="bg-blue-50 border border-blue-200 text-blue-800 p-4 rounded">
            <strong>Generation in progress.</strong>
            <span class="text-sm">Refresh in a few seconds — the schematic build job is running.</span>
        </div>
    @elseif ($drawing->isFailed())
        <div class="bg-red-50 border border-red-200 text-red-800 p-4 rounded">
            <strong>Generation failed.</strong>
            <p class="text-sm mt-1">{{ $drawing->error_message ?? 'Unknown error — see queue worker logs.' }}</p>
        </div>
    @else
        <div class="bg-gray-50 border border-gray-200 text-gray-700 p-4 rounded">
            <strong>No SVG output yet.</strong>
            <span class="text-sm">This drawing is in {{ $drawing->statusLabel() }} state.</span>
        </div>
    @endif

    {{-- ───── Workflow status form (DRAW-25 — set_status via DocumentEditAdapter) ───── --}}
    <form method="POST" action="{{ route('projects.drawings.update-status', [$project, $drawing]) }}"
          class="mt-6 flex items-center gap-2 flex-wrap">
        @csrf
        @method('PUT')
        <label for="status" class="text-sm font-medium text-gray-700">Workflow status:</label>
        <select name="status" id="status" class="border border-gray-300 rounded px-2 py-1 text-sm">
            <option value="draft"      @selected($drawing->status === \App\Models\ProjectDrawing::STATUS_DRAFT)>Draft</option>
            <option value="for_review" @selected($drawing->status === \App\Models\ProjectDrawing::STATUS_FOR_REVIEW)>For Review</option>
            <option value="approved"   @selected($drawing->status === \App\Models\ProjectDrawing::STATUS_APPROVED)>Approved</option>
        </select>
        <button type="submit" class="inline-flex items-center border border-gray-300 hover:bg-gray-50 text-gray-700 px-3 py-1 rounded-md text-sm">
            Update
        </button>
        <p class="text-xs text-gray-500 ml-2">"Superseded" is set automatically when this drawing is regenerated.</p>
    </form>

    {{-- DRAW-30 chat scaffolding hook — Phase 19 plugs the editor + chat in.
         TODO Phase 19: include('document-edit-drawer', ['documentType' => 'drawing', 'documentId' => $drawing->id])
         The DrawingEditAdapter is already registered in DocumentEditAdapterRegistry
         (Plan 17-01), so the drawer needs no controller changes — only the
         functional Konva editor needs to land before this is enabled. --}}

    @include('projects.drawings._regenerate-confirm-modal', ['project' => $project])
</div>
@endsection
