<?php

namespace Tests\Feature\Drawings;

use App\Models\DeviceStencil;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

/**
 * Phase 24 Plan 03 (DRAW-50) — /admin/device-stencils list view.
 *
 * Covers the admin gate (inherited from the existing 'admin' route-group
 * middleware — no new auth code written per T-24-06), the source /
 * needs_review / manufacturer filters, the part_number search, and both
 * distinct empty-state copy blocks from 24-UI-SPEC.md's Copywriting
 * Contract table.
 *
 * @see app/Http/Controllers/Admin/DeviceStencilController.php
 * @see resources/views/admin/device-stencils/index.blade.php
 * @see .planning/phases/24-stencil-curation-ui-quote-import-auto-stub/24-03-PLAN.md
 */
class DeviceStencilListTest extends TestCase
{
    use RefreshDatabase;

    private User $admin;

    private User $user;

    private function makeStencil(array $overrides = []): DeviceStencil
    {
        return DeviceStencil::create(array_merge([
            'part_number'    => 'PN-'.fake()->unique()->numerify('#####'),
            'manufacturer'   => 'Neat',
            'model'          => 'Bar Pro',
            'display_name'   => null,
            'mxgraph_xml'    => '<shape name="21cav.test" h="140" w="220" aspect="variable" strokewidth="inherit"><background/><foreground/></shape>',
            'default_width'  => 220,
            'default_height' => 140,
            'source'         => DeviceStencil::SOURCE_AUTO_GENERATED,
            'needs_review'   => false,
        ], $overrides));
    }

    protected function setUp(): void
    {
        parent::setUp();

        $this->admin = User::factory()->create(['role' => 'admin']);
        $this->user  = User::factory()->create(['role' => 'user']);
    }

    // ── admin gate ───────────────────────────────────────────────────────

    public function test_non_admin_cannot_access_device_stencils_index(): void
    {
        $this->actingAs($this->user)
            ->get(route('admin.device-stencils.index'))
            ->assertForbidden();
    }

    // ── criterion 1: full list renders every stencil ────────────────────

    public function test_index_lists_every_stencil(): void
    {
        $autoNeedsReview = $this->makeStencil([
            'part_number'  => 'PN-AUTO-1',
            'source'       => DeviceStencil::SOURCE_AUTO_GENERATED,
            'needs_review' => true,
        ]);
        $engineerCurated = $this->makeStencil([
            'part_number' => 'PN-CURATED-1',
            'source'      => DeviceStencil::SOURCE_ENGINEER_CURATED,
        ]);
        $distinctManufacturer = $this->makeStencil([
            'part_number'  => 'PN-DISTINCT-1',
            'manufacturer' => 'Samsung',
        ]);

        $response = $this->actingAs($this->admin)
            ->get(route('admin.device-stencils.index'))
            ->assertOk();

        $response->assertSee($autoNeedsReview->part_number);
        $response->assertSee($engineerCurated->part_number);
        $response->assertSee($distinctManufacturer->part_number);
        $response->assertSee('Needs review');
    }

    // ── criterion 2: source / needs_review / manufacturer filters ───────

    public function test_source_filter_narrows_to_that_source_only(): void
    {
        $autoGenerated = $this->makeStencil(['part_number' => 'PN-AUTO-2']);
        $engineerCurated = $this->makeStencil([
            'part_number' => 'PN-CURATED-2',
            'source'      => DeviceStencil::SOURCE_ENGINEER_CURATED,
        ]);

        $response = $this->actingAs($this->admin)
            ->get(route('admin.device-stencils.index', ['source' => DeviceStencil::SOURCE_ENGINEER_CURATED]))
            ->assertOk();

        $response->assertSee($engineerCurated->part_number);
        $response->assertDontSee($autoGenerated->part_number);
    }

    public function test_needs_review_and_manufacturer_filters_combine(): void
    {
        $match = $this->makeStencil([
            'part_number'  => 'PN-MATCH-1',
            'manufacturer' => 'Neat',
            'source'       => DeviceStencil::SOURCE_AUTO_GENERATED,
            'needs_review' => true,
        ]);
        $wrongManufacturer = $this->makeStencil([
            'part_number'  => 'PN-WRONG-MFR',
            'manufacturer' => 'Samsung',
            'source'       => DeviceStencil::SOURCE_AUTO_GENERATED,
            'needs_review' => true,
        ]);
        $notNeedingReview = $this->makeStencil([
            'part_number'  => 'PN-NOT-NEEDED',
            'manufacturer' => 'Neat',
            'source'       => DeviceStencil::SOURCE_AUTO_GENERATED,
            'needs_review' => false,
        ]);

        $response = $this->actingAs($this->admin)
            ->get(route('admin.device-stencils.index', [
                'source'       => DeviceStencil::SOURCE_AUTO_GENERATED,
                'needs_review' => '1',
                'manufacturer' => 'Neat',
            ]))
            ->assertOk();

        $response->assertSee($match->part_number);
        $response->assertDontSee($wrongManufacturer->part_number);
        $response->assertDontSee($notNeedingReview->part_number);
    }

    // ── criterion 2: part_number search ──────────────────────────────────

    public function test_q_search_matches_part_number_substring_only(): void
    {
        $match = $this->makeStencil([
            'part_number'  => 'NEAT-BAR-PRO',
            'manufacturer' => 'Neat',
        ]);
        $noMatch = $this->makeStencil([
            'part_number'  => 'SAM-QM65',
            'manufacturer' => 'Samsung',
        ]);

        $response = $this->actingAs($this->admin)
            ->get(route('admin.device-stencils.index', ['q' => 'bar-pro']))
            ->assertOk();

        $response->assertSee($match->part_number);
        $response->assertDontSee($noMatch->part_number);
    }

    public function test_q_search_does_not_match_manufacturer_or_model(): void
    {
        $stencil = $this->makeStencil([
            'part_number'  => 'PN-99',
            'manufacturer' => 'Neat',
            'model'        => 'Bar Pro',
        ]);

        $this->actingAs($this->admin)
            ->get(route('admin.device-stencils.index', ['q' => 'neat']))
            ->assertOk()
            ->assertDontSee($stencil->part_number);
    }

    // ── unfiltered empty state (positive-tone) ───────────────────────────

    public function test_unfiltered_empty_state_shows_positive_tone_copy(): void
    {
        $response = $this->actingAs($this->admin)
            ->get(route('admin.device-stencils.index'))
            ->assertOk();

        $response->assertSee('No stencils awaiting curation.');
        $response->assertSee('Every auto-generated stub has been promoted. New stubs appear here automatically when a quote import references an uncatalogued part number.');
    }

    // ── filtered empty state (zero matches) ──────────────────────────────

    public function test_filtered_empty_state_shows_clear_filters_link(): void
    {
        $this->makeStencil(['part_number' => 'PN-EXISTS']);

        $response = $this->actingAs($this->admin)
            ->get(route('admin.device-stencils.index', ['q' => 'nomatch123']))
            ->assertOk();

        $response->assertSee('No stencils match your filters.');
        $response->assertSee('Clear filters');
    }
}
